import { mkdirSync, writeFileSync } from 'fs'
import { join, relative } from 'path'
import type { WorkflowState, WorkflowArtifact } from '../../adapters/types'

export interface DocumentEntry {
  phase: string
  title: string
  content: string
}

/**
 * Workflow documents land in the project's `docs/vectalon/<workflow>/<run>/`
 * directory so the team sees them in version control — the `.vectalon/`
 * workspace is gitignored runtime state.
 */
export function workflowDocsDir(projectRoot: string, workflowId: string, workflowRunId: string): string {
  return join(projectRoot, 'docs', 'vectalon', workflowId, workflowRunId)
}

export function writeWorkflowDocuments(
  projectRoot: string,
  workflowId: string,
  workflowRunId: string,
  documents: DocumentEntry[]
): string[] {
  const docsDir = workflowDocsDir(projectRoot, workflowId, workflowRunId)
  mkdirSync(docsDir, { recursive: true })

  const written: string[] = []
  for (const doc of documents) {
    const fileName = `${doc.phase.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md`
    const filePath = join(docsDir, fileName)
    const header = `# ${doc.title}\n\n`
    writeFileSync(filePath, header + doc.content)
    written.push(filePath)
  }

  return written
}

export function writePhaseDocument(
  projectRoot: string,
  workflowId: string,
  workflowRunId: string,
  phase: string,
  title: string,
  content: string
): string {
  const docsDir = workflowDocsDir(projectRoot, workflowId, workflowRunId)
  mkdirSync(docsDir, { recursive: true })

  const fileName = `${phase.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md`
  const filePath = join(docsDir, fileName)
  const header = `# ${title}\n\n`
  writeFileSync(filePath, header + content)
  return filePath
}

/**
 * Write `index.md` into a workflow's docs directory — the single link that
 * previews every document a run produced (PRD, design, tests, verification
 * report, …) plus the files it created. Returns the index path.
 */
export function writeWorkflowIndex(
  projectRoot: string,
  workflowId: string,
  workflowRunId: string,
  state: WorkflowState,
  artifacts: WorkflowArtifact[],
  extra: { prompt: string; model?: string; status?: string }
): string {
  const docsDir = workflowDocsDir(projectRoot, workflowId, workflowRunId)
  mkdirSync(docsDir, { recursive: true })

  const docArtifacts = artifacts.filter(a => a.path && a.type === 'document')
  const fileArtifacts = artifacts.filter(a => a.path && a.type !== 'document')

  const lines: string[] = [
    `# Workflow: ${state.workflowId} — ${workflowRunId}`,
    '',
    `- **Status:** ${extra.status ?? state.status}`,
    `- **Model:** ${extra.model ?? 'unknown'}`,
    `- **Prompt:** ${extra.prompt}`, '']

  lines.push('## Documents')
  if (docArtifacts.length === 0) {
    lines.push('', '_No documents were produced by this run._')
  } else {
    for (const artifact of docArtifacts) {
      const rel = relative(docsDir, artifact.path as string)
      lines.push(`- [${artifact.title}](${rel})`)
    }
  }

  if (fileArtifacts.length > 0) {
    lines.push('', '## Files created or modified')
    for (const artifact of fileArtifacts) {
      const rel = relative(projectRoot, artifact.path as string)
      lines.push(`- \`${rel}\``)
    }
  }

  lines.push('', `_Generated by vectalon ${new Date().toISOString()}._`)

  const indexPath = join(docsDir, 'index.md')
  writeFileSync(indexPath, lines.join('\n') + '\n')
  return indexPath
}
