import { logger } from '../../cli/logger'
import { basename } from 'path'
import type { WorkflowPhase, WorkflowContext } from '../../adapters/types'
import { ensureCiConfigs } from '../../adapters/ciTemplates'
import { phaseResult, failedPhase, sanitizeFileName } from './helpers'
import { getIntent, intentTitle } from './intent'

const CHECKLIST = [
  '- [x] PRD generated',
  '- [x] Design/UX approach defined',
  '- [x] Architecture decision recorded',
  '- [x] Tests written first (TDD)',
  '- [x] Implementation generated to satisfy tests',
  '- [x] Code review passed',
  '- [x] Verification completed (tests, lint, typecheck)',
]

function phaseOutput(ctx: WorkflowContext, id: string): string {
  return ctx.state.phases.find(p => p.id === id)?.output || ''
}

/** Extract the review summary line (e.g. `**Summary:** 0 error(s), …`) from the report. */
function reviewSummary(output: string): string {
  const match = output.match(/\*\*Summary:\*\* ([^\n]+)/)
  return match ? match[1] : ''
}

/** Extract the `- Attempt N: …` / `- file: fixed …` self-healing log lines. */
function healLogLines(output: string): string[] {
  const section = output.split('## Self-healing')[1]?.split('##')[0] || ''
  return section
    .split('\n')
    .map(l => l.trim())
    .filter(l => /^-/.test(l))
}

function changedFiles(ctx: WorkflowContext): string[] {
  // The code-review phase heals BOTH implementation and test artifacts, so the
  // commit (and PR body) must list test-phase files too or their fixes would
  // be left unstaged on the pushed branch.
  const paths = [
    ...(ctx.state.phases.find(p => p.id === 'implementation')?.artifacts || []),
    ...(ctx.state.phases.find(p => p.id === 'tests')?.artifacts || []),
    // Verification screenshots (visual diff + impact regression flows) are
    // tracked into docs/vectalon/.../screenshots/ — commit them so they render
    // on the PR. Paths still under .vectalon/ (gitignored) are excluded: an
    // explicit `git add` of an ignored file would fail the commit.
    ...(ctx.state.phases.find(p => p.id === 'verification')?.artifacts || []).filter(
      a => a.type === 'design' && a.path && !a.path.startsWith('.vectalon')
    ),
  ]
    .map(a => a.path)
    .filter((p): p is string => !!p)
  return paths.length > 0 ? paths : ['(see diff)']
}

/** Screenshot artifacts the verification phase tracked for the PR. */
function prScreenshots(ctx: WorkflowContext): string[] {
  return (ctx.state.phases.find(p => p.id === 'verification')?.artifacts || [])
    .filter(a => a.type === 'design' && a.path && /\.png$/i.test(a.path) && !a.path.startsWith('.vectalon'))
    .map(a => a.path as string)
}

/** Build the PR body: what changed, why (from the heal loop + verification), checklist. */
type WorkflowIntent = Awaited<ReturnType<typeof getIntent>>['intent']

function buildPrBody(ctx: WorkflowContext, intent: WorkflowIntent, ciFiles: string[]): string {
  const reviewOutput = phaseOutput(ctx, 'code-review')
  const verificationOutput = phaseOutput(ctx, 'verification')
  const summary = reviewSummary(reviewOutput)
  const heals = healLogLines(reviewOutput)

  const why: string[] = []
  if (summary) {
    why.push(`Code review: ${summary}`)
  }
  if (heals.length > 0) {
    why.push('', 'Self-healing fixes applied during review:')
    why.push(...heals.map(h => `- ${h.replace(/^-/, '').trim()}`))
  }
  const verificationSummary = verificationOutput
    .split('\n')
    .find(line => /(passed|failed) \(exit/i.test(line))
  if (verificationSummary) {
    why.push('', verificationSummary.trim())
  }
  if (why.length === 0) {
    why.push('Generated by the vectalon feature workflow; review the diff for details.')
  }

  return [
    `## ${intentTitle(intent)}`,
    '',
    ctx.prompt,
    '',
    '## What changed',
    ...changedFiles(ctx).map(f => `- ${f}`),
    ...(ciFiles.length > 0 ? ['', ...ciFiles.map(f => `- ${f} (generated CI workflow)`)] : []),
    '',
    '## Why',
    ...why,
    '',
    ...(() => {
      const shots = prScreenshots(ctx)
      return shots.length > 0
        ? ['## Screenshots', '', ...shots.map(s => `![${basename(s)}](${s})`), '', 'Visual diff + impact regression screenshots from verification.']
        : []
    })(),
    '## Checklist',
    ...CHECKLIST,
    '',
  ].join('\n')
}

export const prPhase: WorkflowPhase = {
  id: 'pr',
  name: 'Pull request',
  description: 'Create a branch, commit changes, and open a pull request.',
  run: async (ctx) => {
    const intent = (await getIntent(ctx)).intent
    const featureName = sanitizeFileName(ctx.prompt) || 'feature'
    const branchName = `feature/${featureName}-${Date.now()}`

    try {
      // Generate the project's CI workflow (EAS Workflows for Expo, GitHub
      // Actions for bare RN CLI) before the commit so CI ships with the branch.
      // Idempotent — never overwrites an existing workflow.
      const isExpo = Boolean(
        ctx.snapshot?.project.expoSdkVersion ||
        ctx.snapshot?.project.dependencies.expo ||
        ctx.snapshot?.project.devDependencies.expo
      )
      // CI workflow files are generated on real (non dry-run) runs only, so a
      // `--dry-run` feature run never writes `.github/` / `.eas/` to disk.
      const dryRun = ctx.adapters.git.name === 'console'
      const ciFiles = ctx.projectRoot && !dryRun
        ? ensureCiConfigs(ctx.projectRoot, { isExpo }).filter(f => f.written).map(f => f.path)
        : []

      await ctx.adapters.git.createBranch(branchName)

      const files = [...changedFiles(ctx), ...ciFiles]

      const commitPrefix = intent.type === 'remove-dependency' ? 'chore' : intent.type === 'fix' ? 'fix' : 'feat'

      await ctx.adapters.git.commit({
        message: `${commitPrefix}: ${ctx.prompt}`,
        files,
      })
      await ctx.adapters.git.push(branchName)

      const pr = await ctx.adapters.git.createPullRequest({
        title: `${commitPrefix}: ${ctx.prompt}`,
        body: buildPrBody(ctx, intent, ciFiles),
        head: branchName,
      })

      // Review comment describing what changed and why — the code-review
      // report (findings + self-healing log) posted onto the PR. Best-effort:
      // a comment failure must never fail the phase after the PR was created.
      if (pr) {
        const reviewOutput = phaseOutput(ctx, 'code-review')
        if (reviewOutput) {
          try {
            await ctx.adapters.git.commentPullRequest(pr.number, `## Code review\n\n${reviewOutput.slice(0, 4000)}`)
          } catch (err) {
            logger.warn(`Could not post code-review comment on PR #${pr.number}: ${err instanceof Error ? err.message : String(err)}`)
          }
        }
      }

      const output = [
        `Branch: ${branchName}`,
        pr ? `Pull request: ${pr.url}` : 'Pull request: not created (set GITHUB_TOKEN or install `gh` to open one automatically)',
        `Title: ${commitPrefix}: ${ctx.prompt}`,
        ...(ciFiles.length > 0 ? [`CI workflow: ${ciFiles.join(', ')}`] : []),
      ].join('\n')

      return phaseResult(
        'pr',
        'Pull request',
        'Create a branch, commit changes, and open a pull request.',
        output,
        [{ type: 'devops', title: `PR: ${ctx.prompt}`, content: output }]
      )
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      return failedPhase('pr', 'Pull request', 'Create a branch, commit changes, and open a pull request.', message)
    }
  },
}
