import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { implementationPhase } from '../../src/workflows/phases/implementationPhase'
import { ModelRouter } from '../../src/model/ModelRouter'
import type { WorkflowContext } from '../../src/adapters/types'

// Intent always comes from the LLM, so the first generate() call is consumed
// by intent detection. These legacy tests were written before intent routing
// existed, so prepend an add-feature intent and let every subsequent call
// return the model response under test.
function createMockModelRouter(response: string): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  const mock = jest.spyOn(router, 'generate')
  mock.mockResolvedValueOnce({
    content: JSON.stringify({ intents: [{ type: 'add-feature', feature: 'login', confidence: 1, reasoning: 'new feature' }] }),
    provider: 'mock',
  })
  mock.mockResolvedValue({ content: response, provider: 'local' })
  return router
}

// Intent always comes from the LLM, so tests that exercise a specific intent
// must feed intent JSON to the first generate() call and the implementation
// response to subsequent calls.
function createMockModelRouterSequence(responses: string[]): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  const mock = jest.spyOn(router, 'generate')
  for (const content of responses) {
    mock.mockResolvedValueOnce({ content, provider: 'mock' })
  }
  return router
}

function createContext(modelRouter: ModelRouter, prompt: string, projectRoot: string): WorkflowContext {
  return {
    projectRoot,
    snapshot: {
      project: {
        root: projectRoot,
        name: 'test-app',
        version: '1.0.0',
        reactNativeVersion: '0.72.0',
        dependencies: {},
        devDependencies: {},
        scripts: {},
        platforms: ['ios', 'android'],
        hasTypeScript: true,
        hasMetro: true,
        hasExpo: false,
        tooling: 'rn-cli',
        expoSdkVersion: '',
      },
      structure: [],
      components: [],
      recentChanges: [],
      timestamp: Date.now(),
    },
    prompt,
    inputs: {},
    outputs: {},
    state: {
      id: 'test',
      workflowId: 'feature-development',
      prompt,
      status: 'running',
      phases: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    adapters: {
      projectManagement: { name: 'mock', createTasks: jest.fn(), updateTasks: jest.fn(), closeTasks: jest.fn() },
      git: { name: 'mock', createBranch: jest.fn(), commit: jest.fn(), push: jest.fn(), createPullRequest: jest.fn() },
      testRunner: { name: 'mock', runTests: jest.fn() },
      simulator: { name: 'mock', run: jest.fn() },
      design: { name: 'mock', analyzeMotion: jest.fn() },
    },
    modelRouter,
  }
}

describe('implementationPhase', () => {
  let tmpDir: string
  let projectRoot: string

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'vectalon-impl-'))
    projectRoot = tmpDir
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  it('uses model-generated code when the model returns valid JSON', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
      notes: 'Generated by model',
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Generated by model')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBe('src/screens/AddLoginScreenScreen.tsx')
  })

  it('writes model-generated JSON files to disk', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
    })
    const router = createMockModelRouter(response)
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')
    expect(readFileSync(screenPath, 'utf-8')).toContain('export function LoginScreen')
  })

  it('parses markdown sections with ### paths and fenced code into files on disk', async () => {
    const response = [
      'Here are the files:',
      '',
      '### src/services/AddLoginScreenApi.ts',
      '```typescript',
      'export class AddLoginScreenApi { async execute() { return "ok" } }',
      '```',
      '',
      '### src/screens/AddLoginScreenScreen.tsx',
      '```tsx',
      'export function AddLoginScreenScreen() { return null }',
      '```',
    ].join('\n')
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts).toHaveLength(2)
    const servicePath = join(projectRoot, 'src/services/AddLoginScreenApi.ts')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')
    expect(readFileSync(servicePath, 'utf-8')).toContain('class AddLoginScreenApi')
    expect(readFileSync(screenPath, 'utf-8')).toContain('AddLoginScreenScreen')
    expect(result.output).toContain('Files written to disk')
  })

  it('parses bare path lines followed by fenced code blocks', async () => {
    const response = [
      'src/hooks/useAddLoginScreen.ts',
      '```ts',
      'export function useAddLoginScreen() { return { run: async () => "ok" } }',
      '```',
    ].join('\n')
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts).toHaveLength(1)
    const hookPath = join(projectRoot, 'src/hooks/useAddLoginScreen.ts')
    expect(readFileSync(hookPath, 'utf-8')).toContain('useAddLoginScreen')
  })

  it('preserves unparseable model output as a note instead of discarding it', async () => {
    const router = createMockModelRouter('the login screen should use email and password fields with validation')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Model output (not applied)')
    expect(result.output).toContain('email and password fields')
    // Still falls back to the deterministic scaffold so the phase produces runnable files
    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })

  it('rejects path traversal and absolute paths from model output', async () => {
    const response = JSON.stringify({
      files: [
        { path: '../evil.ts', content: 'export const evil = 1' },
        { path: '/etc/hosts.ts', content: 'export const hosts = 1' },
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    // Safe file written; unsafe paths filtered out entirely
    expect(readFileSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'), 'utf-8')).toContain('LoginScreen')
    expect(result.artifacts.map(a => a.path)).toEqual(['src/screens/AddLoginScreenScreen.tsx'])
    expect(existsSync(join(projectRoot, '../evil.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'etc/hosts.ts'))).toBe(false)
  })

  it('drops JSON entries that lack string content', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/services/AddLoginScreenApi.ts', content: 'export class AddLoginScreenApi {}' },
        { path: 'src/hooks/useAddLoginScreen.ts' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts.map(a => a.path)).toEqual(['src/services/AddLoginScreenApi.ts'])
    expect(readFileSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'), 'utf-8')).toContain('AddLoginScreenApi')
  })

  it('keeps generated scaffold out of src/ when the project is the rn-vectalon package itself', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: '@vectalon-dev/rn-vectalon', version: '0.5.0' }))

    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('.vectalon/generated')
    // Nothing written into the package's own src/
    expect(existsSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/hooks/useAddLoginScreen.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'))).toBe(false)
    // Generated files land in the gitignored output dir instead
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/services/AddLoginScreenApi.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/hooks/useAddLoginScreen.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/screens/AddLoginScreenScreen.tsx'))).toBe(true)
  })

  it('keeps model-generated files out of src/ when the project is the rn-vectalon package itself', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: '@vectalon-dev/rn-vectalon', version: '0.5.0' }))
    const response = JSON.stringify({
      files: [{ path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' }],
    })
    const router = createMockModelRouter(response)
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(existsSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'))).toBe(false)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/screens/AddLoginScreenScreen.tsx'))).toBe(true)
  })

  it('still writes into src/ for a regular React Native project', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: 'my-app', version: '1.0.0' }))

    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(existsSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/services/AddLoginScreenApi.ts'))).toBe(false)
    expect(result.output).not.toContain('.vectalon/generated')
  })

  it('falls back to deterministic scaffold when the model returns fallback marker', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
    expect(result.output).toContain('src/hooks/useAddLoginScreen.ts')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.output).toContain('Files written to disk')
  })

  it('falls back to deterministic scaffold when the model returns unparseable JSON', async () => {
    const router = createMockModelRouter('some plain text without json')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })

  it('writes generated scaffold files to disk for add-feature', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    const servicePath = join(projectRoot, 'src/services/AddLoginScreenApi.ts')
    const hookPath = join(projectRoot, 'src/hooks/useAddLoginScreen.ts')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')

    expect(readFileSync(servicePath, 'utf-8')).toContain('class AddLoginScreenApi')
    expect(readFileSync(hookPath, 'utf-8')).toContain('useAddLoginScreen')
    expect(readFileSync(screenPath, 'utf-8')).toContain('AddLoginScreenScreen')
  })

  it('removes unused imports when the intent is refactor remove-unused-imports', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    const filePath = join(srcDir, 'Example.tsx')
    writeFileSync(
      filePath,
      [
        "import React from 'react';",
        "import { View, Text } from 'react-native';",
        "import { unusedHelper } from './helpers';",
        '',
        'export function Example() {',
        '  return <View><Text>Hi</Text></View>;',
        '}',
      ].join('\n')
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'refactor', target: 'remove-unused-imports', confidence: 1, reasoning: 'unused imports to remove' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'remove unused imports throughout the app', projectRoot))

    expect(result.output).toContain('Refactor: remove unused imports')
    expect(result.output).toContain('Files modified')
    expect(result.output).toContain(filePath)

    const updated = readFileSync(filePath, 'utf-8')
    expect(updated).toContain("import { View, Text } from 'react-native';")
    expect(updated).not.toContain("import { unusedHelper } from './helpers';")
  })

  it('reports guardrail summary for generated scaffold', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('All guardrails passed')
  })

  it('reports guardrail findings for model-generated code with violations', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/BadScreen.tsx', content: 'export function BadScreen() { console.log("hi"); return null; }' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a bad screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('No console.log statements')
    expect(result.output).toContain('1 error(s)')
  })

  it('routes lint-fix requests to the fix path and repairs existing files without scaffolding', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
      JSON.stringify({
        files: [
          { path: 'src/screens/Home.tsx', content: 'export function Home() { return null }' },
        ],
      }),
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: false,
        stdout: '',
        stderr: 'src/screens/Home.tsx:3:5 - Unexpected console statement (no-console)',
        exitCode: 1,
      }),
    }

    const result = await implementationPhase.run(ctx)

    // The repaired file was written to disk
    expect(result.artifacts.map(a => a.path)).toEqual(['src/screens/Home.tsx'])
    expect(readFileSync(join(projectRoot, 'src/screens/Home.tsx'), 'utf-8')).toContain('export function Home')
    // No scaffold files were created for the request
    expect(existsSync(join(projectRoot, 'src/services/FixAllLintIssuesApi.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/hooks/useFixAllLintIssues.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/screens/FixAllLintIssuesScreen.tsx'))).toBe(false)
  })

  it('never scaffolds new files for a lint-fix request when the model cannot produce a fix', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
      'this model output cannot be parsed into files',
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: false,
        stdout: '',
        stderr: 'src/screens/Home.tsx:3:5 - Unexpected console statement (no-console)',
        exitCode: 1,
      }),
    }

    const result = await implementationPhase.run(ctx)

    expect(result.output).toContain('Fix lint issues')
    expect(result.output).toContain('No files were created or modified')
    expect(result.output).toContain('no-console')
    // Nothing was written to disk at all
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
  })

  it('reports a clean check for a lint-fix request when lint already passes', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: true,
        stdout: 'No lint issues',
        stderr: '',
        exitCode: 0,
      }),
    }

    const result = await implementationPhase.run(ctx)

    expect(result.output).toContain('passes cleanly')
    expect(result.output).toContain('Nothing to fix')
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
  })

  it('produces a clarification plan and writes NO files when the intent is unknown', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'unknown', confidence: 0.5, reasoning: 'not sure' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'Remove appcenter safely from this project', projectRoot))

    expect(result.output).toContain('Request not classified')
    expect(result.output).toContain('no files were created or modified')
    // Nothing was written to disk at all
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
    // No scaffold artifacts for the unknown request
    expect(result.artifacts.filter(a => a.type === 'engineering')).toHaveLength(1)
    expect(result.artifacts[0].title).toBe('Clarification needed')
  })
})
