import { implementationPhase } from '../../src/workflows/phases/implementationPhase'
import { ModelRouter } from '../../src/model/ModelRouter'
import type { WorkflowContext } from '../../src/adapters/types'

function createMockModelRouter(response: string): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  jest.spyOn(router, 'generate').mockResolvedValue({ content: response, provider: 'local' })
  return router
}

function createContext(modelRouter: ModelRouter): WorkflowContext {
  return {
    projectRoot: '/tmp/test',
    snapshot: {
      project: {
        root: '/tmp/test',
        name: 'test-app',
        version: '1.0.0',
        reactNativeVersion: '0.72.0',
        dependencies: {},
        devDependencies: {},
        scripts: {},
        platforms: ['ios', 'android'],
        hasTypeScript: true,
        hasMetro: true,
        hasExpo: false,
      },
      structure: [],
      components: [],
      recentChanges: [],
      timestamp: Date.now(),
    },
    prompt: 'Add a login screen',
    inputs: {},
    outputs: {},
    state: {
      id: 'test',
      workflowId: 'feature-development',
      prompt: 'Add a login screen',
      status: 'running',
      phases: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    adapters: {
      projectManagement: { name: 'mock', createTasks: jest.fn(), updateTasks: jest.fn(), closeTasks: jest.fn() },
      git: { name: 'mock', createBranch: jest.fn(), commit: jest.fn(), push: jest.fn(), createPullRequest: jest.fn() },
      testRunner: { name: 'mock', runTests: jest.fn() },
      simulator: { name: 'mock', run: jest.fn() },
      design: { name: 'mock', analyzeMotion: jest.fn() },
    },
    modelRouter,
  }
}

describe('implementationPhase', () => {
  it('uses model-generated code when the model returns valid JSON', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
      notes: 'Generated by model',
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router))

    expect(result.output).toContain('Generated by model')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBe('src/screens/AddLoginScreenScreen.tsx')
  })

  it('falls back to deterministic scaffold when the model returns fallback marker', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
    expect(result.output).toContain('src/hooks/useAddLoginScreen.ts')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
  })

  it('falls back to deterministic scaffold when the model returns unparseable JSON', async () => {
    const router = createMockModelRouter('some plain text without json')
    const result = await implementationPhase.run(createContext(router))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })
})
