import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { implementationPhase } from '../../src/workflows/phases/implementationPhase'
import { ModelRouter } from '../../src/model/ModelRouter'
import type { WorkflowContext } from '../../src/adapters/types'

function createMockModelRouter(response: string): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  jest.spyOn(router, 'generate').mockResolvedValue({ content: response, provider: 'local' })
  return router
}

function createContext(modelRouter: ModelRouter, prompt: string, projectRoot: string): WorkflowContext {
  return {
    projectRoot,
    snapshot: {
      project: {
        root: projectRoot,
        name: 'test-app',
        version: '1.0.0',
        reactNativeVersion: '0.72.0',
        dependencies: {},
        devDependencies: {},
        scripts: {},
        platforms: ['ios', 'android'],
        hasTypeScript: true,
        hasMetro: true,
        hasExpo: false,
      },
      structure: [],
      components: [],
      recentChanges: [],
      timestamp: Date.now(),
    },
    prompt,
    inputs: {},
    outputs: {},
    state: {
      id: 'test',
      workflowId: 'feature-development',
      prompt,
      status: 'running',
      phases: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    adapters: {
      projectManagement: { name: 'mock', createTasks: jest.fn(), updateTasks: jest.fn(), closeTasks: jest.fn() },
      git: { name: 'mock', createBranch: jest.fn(), commit: jest.fn(), push: jest.fn(), createPullRequest: jest.fn() },
      testRunner: { name: 'mock', runTests: jest.fn() },
      simulator: { name: 'mock', run: jest.fn() },
      design: { name: 'mock', analyzeMotion: jest.fn() },
    },
    modelRouter,
  }
}

describe('implementationPhase', () => {
  let tmpDir: string
  let projectRoot: string

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'vectalon-impl-'))
    projectRoot = tmpDir
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  it('uses model-generated code when the model returns valid JSON', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
      notes: 'Generated by model',
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Generated by model')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBe('src/screens/AddLoginScreenScreen.tsx')
  })

  it('falls back to deterministic scaffold when the model returns fallback marker', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
    expect(result.output).toContain('src/hooks/useAddLoginScreen.ts')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.output).toContain('Files written to disk')
  })

  it('falls back to deterministic scaffold when the model returns unparseable JSON', async () => {
    const router = createMockModelRouter('some plain text without json')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })

  it('writes generated scaffold files to disk for add-feature', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    const servicePath = join(projectRoot, 'src/services/AddLoginScreenApi.ts')
    const hookPath = join(projectRoot, 'src/hooks/useAddLoginScreen.ts')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')

    expect(readFileSync(servicePath, 'utf-8')).toContain('class AddLoginScreenApi')
    expect(readFileSync(hookPath, 'utf-8')).toContain('useAddLoginScreen')
    expect(readFileSync(screenPath, 'utf-8')).toContain('AddLoginScreenScreen')
  })

  it('removes unused imports when the intent is refactor remove-unused-imports', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    const filePath = join(srcDir, 'Example.tsx')
    writeFileSync(
      filePath,
      [
        "import React from 'react';",
        "import { View, Text } from 'react-native';",
        "import { unusedHelper } from './helpers';",
        '',
        'export function Example() {',
        '  return <View><Text>Hi</Text></View>;',
        '}',
      ].join('\n')
    )

    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'remove unused imports throughout the app', projectRoot))

    expect(result.output).toContain('Refactor: remove unused imports')
    expect(result.output).toContain('Files modified')
    expect(result.output).toContain(filePath)

    const updated = readFileSync(filePath, 'utf-8')
    expect(updated).toContain("import { View, Text } from 'react-native';")
    expect(updated).not.toContain("import { unusedHelper } from './helpers';")
  })

  it('reports guardrail summary for generated scaffold', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('All guardrails passed')
  })

  it('reports guardrail findings for model-generated code with violations', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/BadScreen.tsx', content: 'export function BadScreen() { console.log("hi"); return null; }' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a bad screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('No console.log statements')
    expect(result.output).toContain('1 error(s)')
  })
})
