/**
 * vectalon ci — Self-healing CI generation
 * Business Source License 1.1 (BSL-1.1)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'
import { requireTier } from '@vectalon/core'
import { logger } from '../logger'

interface CiOptions {
  dryRun?: boolean
}

function isExpoProject(dir: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf-8'))
    return !!pkg.dependencies?.expo || !!pkg.devDependencies?.expo
  } catch {
    return false
  }
}

function isReactNativeCLIProject(dir: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf-8'))
    return !!pkg.dependencies?.['react-native'] && !pkg.dependencies?.expo
  } catch {
    return false
  }
}

export async function ciCommand(directory: string, options: CiOptions): Promise<void> {
  const check = requireTier('pro', 'rn', 'ci')

  if (!check.allowed) {
    logger.info('⚡ Self-healing CI requires Pro tier.')
    logger.info(`Current: ${check.currentTier} | Required: ${check.requiredTier}`)

    if (check.canTrial) {
      logger.info('')
      logger.info('🔄 Start 14-day Pro trial?')
      logger.info('   Run: npx vectalon auth --github')
      logger.info('   Or visit: https://vectalon.in/trial?product=rn')
    }

    logger.info('')
    logger.info('💳 Upgrade at: https://vectalon.in/pricing')
    process.exit(1)
  }

  const root = resolve(directory || process.cwd())
  const vectalonDir = join(root, '.vectalon')

  if (!existsSync(vectalonDir)) {
    logger.error('No .vectalon/ directory found. Run `vectalon init` first.')
    process.exit(1)
  }

  logger.info('🔧 Self-healing CI Generator')
  logger.info('   Detecting project tooling...')

  if (options.dryRun) {
    logger.info('   (dry run — no files written)')
    return
  }

  if (isExpoProject(root)) {
    logger.info('   Detected: Expo project → EAS workflow')
    const easDir = join(root, '.eas', 'workflows')
    mkdirSync(easDir, { recursive: true })
    writeFileSync(
      join(easDir, 'vectalon.yml'),
      `# Vectalon CI — Expo EAS workflow\n# Generated by vectalon ci\n`,
      'utf-8'
    )
    logger.info('   Created .eas/workflows/vectalon.yml')
  } else if (isReactNativeCLIProject(root)) {
    logger.info('   Detected: React Native CLI project → GitHub Actions')
    const ghDir = join(root, '.github', 'workflows')
    mkdirSync(ghDir, { recursive: true })
    writeFileSync(
      join(ghDir, 'vectalon-ci.yml'),
      `# Vectalon CI — GitHub Actions workflow\n# Generated by vectalon ci\n`,
      'utf-8'
    )
    logger.info('   Created .github/workflows/vectalon-ci.yml')
  } else {
    logger.warn('   Could not detect project type. Skipping CI generation.')
  }
}
