import type { KnowledgeSource } from './types'

export const defaultSources: KnowledgeSource[] = [
  {
    id: 'react-native-docs',
    name: 'React Native Documentation',
    description: 'Official React Native docs for latest APIs and best practices',
    urls: ['https://reactnative.dev/docs/getting-started'],
    refreshIntervalMs: 7 * 24 * 60 * 60 * 1000,
    type: 'docs',
  },
  {
    id: 'react-navigation-docs',
    name: 'React Navigation Documentation',
    description: 'Official React Navigation docs for routing patterns',
    urls: ['https://reactnavigation.org/docs/getting-started'],
    refreshIntervalMs: 7 * 24 * 60 * 60 * 1000,
    type: 'docs',
  },
  {
    id: 'expo-docs',
    name: 'Expo Documentation',
    description: 'Official Expo docs for managed-workflow best practices',
    urls: ['https://docs.expo.dev/'],
    refreshIntervalMs: 7 * 24 * 60 * 60 * 1000,
    type: 'docs',
  },
  {
    id: 'react-native-registry',
    name: 'React Native npm Registry',
    description: 'Latest published versions of React Native core packages',
    urls: ['https://registry.npmjs.org/react-native/latest'],
    refreshIntervalMs: 24 * 60 * 60 * 1000,
    type: 'registry',
  },
  {
    id: 'react-navigation-registry',
    name: 'React Navigation npm Registry',
    description: 'Latest published versions of React Navigation packages',
    urls: ['https://registry.npmjs.org/@react-navigation/native/latest'],
    refreshIntervalMs: 24 * 60 * 60 * 1000,
    type: 'registry',
  },
  {
    id: 'rn-releases',
    name: 'React Native Releases (GitHub)',
    description: "Official React Native release announcements \u2014 the version map Vectalon's upgrade tooling stays aligned with",
    urls: ['https://github.com/facebook/react-native/releases.atom'],
    refreshIntervalMs: 6 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'expo-changelog',
    name: 'Expo Changelog',
    description: 'Expo SDK changelog — new SDK versions and breaking changes for Expo projects',
    urls: ['https://expo.dev/changelog'],
    refreshIntervalMs: 12 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'rn-blog',
    name: 'React Native Blog',
    description: 'Official React Native engineering blog — architecture, performance, New Architecture updates',
    urls: ['https://reactnative.dev/blog'],
    refreshIntervalMs: 12 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'rn-weekly',
    name: 'React Native Weekly',
    description: "Community newsletter covering the week's React Native ecosystem (libraries, releases, tutorials)",
    urls: ['https://reactnativeweekly.com/'],
    refreshIntervalMs: 12 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'hn-react-native',
    name: 'Hacker News — React Native',
    description: 'Recent Hacker News stories about React Native — community discussions, tooling launches, and ecosystem buzz',
    urls: ['https://hn.algolia.com/api/v1/search_by_date?query=react%20native&tags=story&hitsPerPage=25'],
    refreshIntervalMs: 6 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'github-trending-rn',
    name: 'GitHub — Top React Native Repos',
    description: 'Most-starred React Native repositories on GitHub — new and hot libraries the ecosystem is adopting',
    urls: ['https://api.github.com/search/repositories?q=react-native+in:name,description&sort=stars&order=desc&per_page=20'],
    refreshIntervalMs: 24 * 60 * 60 * 1000,
    type: 'news',
  },
  {
    id: 'callstack-report',
    name: 'Callstack Blog (React Native)',
    description: 'Callstack blog feed — React Native engineering posts, including the monthly Open Source Report of releases and community updates',
    urls: ['https://www.callstack.com/blog/rss.xml'],
    refreshIntervalMs: 12 * 60 * 60 * 1000,
    type: 'news',
  },
]

export function registrySourcesForDependencies(dependencies: string[]): KnowledgeSource[] {
  return dependencies.map(name => ({
    id: `registry-${name.replace(/[@/]/g, '-')}`,
    name: `npm registry: ${name}`,
    description: `Latest published version of ${name}`,
    urls: [`https://registry.npmjs.org/${name.replace('/', '%2F')}/latest`],
    refreshIntervalMs: 24 * 60 * 60 * 1000,
    type: 'registry',
    metadata: { libraryName: name },
  }))
}
