import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import { reportError } from '../utils/safe'

/**
 * The generated Metro reporter that streams build events to the daemon.
 *
 * Metro accepts a custom reporter via the `reporter` option in metro.config.js
 * (`module.exports = { ..., reporter: require('./.vectalon/metro/vectalon-reporter.js') }`
 * — or `vectalon daemon --wire-metro` patches it for you). The reporter reads
 * the daemon's port from `.vectalon/daemon.json` at build time, so a daemon
 * restart with a different port keeps working. It only forwards `bundle_build_done`
 * (with the module composition) and `bundle_build_failed` events; the build
 * works exactly as before if the daemon is offline.
 */

export function metroReporterPath(root: string): string {
  return join(root, '.vectalon', 'metro', 'vectalon-reporter.js')
}

/** The reporter file content (plain CJS — runs inside Metro, not compiled). */
export function buildMetroReporterSource(): string {
  return `// Generated by \`vectalon daemon\` — do not edit.
// Streams Metro build events to the vectalon daemon so bundle-size changes and
// build errors are captured live. Wire it in metro.config.js:
//   module.exports = { ..., reporter: require('./.vectalon/metro/vectalon-reporter.js') }
'use strict'
const fs = require('fs')
const path = require('path')
const http = require('http')

function daemonPort() {
  try {
    const state = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'daemon.json'), 'utf8'))
    return typeof state.port === 'number' ? state.port : null
  } catch (err) {
    return null
  }
}

function post(event) {
  const port = daemonPort()
  if (!port) return
  const body = JSON.stringify(event)
  const req = http.request({
    hostname: '127.0.0.1',
    port,
    path: '/ingest/metro',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(body),
    },
  }, (res) => { res.resume() })
  // The daemon may be offline or hung — the build works regardless. A short
  // timeout prevents a half-dead daemon from pinning sockets in Metro.
  req.setTimeout(2000, () => req.destroy())
  req.on('error', () => {})
  req.end(body)
}

module.exports = ({ reporter }) => {
  reporter.update((event) => {
    if (event.type === 'bundle_build_done' && event.bundleStats) {
      post({
        type: 'bundle_build_done',
        platform: event.platform || 'ios',
        bundleStats: event.bundleStats,
      })
    } else if (event.type === 'bundle_build_failed') {
      const message = event.error && (event.error.message || String(event.error)) || 'unknown build error'
      post({
        type: 'bundle_build_failed',
        platform: event.platform || 'ios',
        error: message,
      })
    }
  })
}
`
}

/** Write the reporter file (idempotent). Returns its path. */
export function writeMetroReporter(root: string): string {
  const file = metroReporterPath(root)
  try {
    mkdirSync(join(root, '.vectalon', 'metro'), { recursive: true })
    writeFileSync(file, buildMetroReporterSource(), 'utf-8')
  } catch (err) {
    reportError(err, 'daemon: writing metro reporter', 'warn')
  }
  return file
}

/** Whether the reporter file already exists on disk. */
export function hasMetroReporter(root: string): boolean {
  return existsSync(metroReporterPath(root))
}
