import type { EcosystemCatalog, EcosystemItem } from './types'

/**
 * Catalog of external MCP servers, agent skills, developer tools, and repo
 * hooks that make an AI agent competent on React Native projects.
 *
 * Sources: expo.dev/docs/mcp, github.com/steve228uk/metro-mcp,
 * github.com/ohah/react-native-mcp, github.com/MrNitro360/React-Native-MCP,
 * github.com/patrickkabwe/react-native-upgrader-mcp, github.com/expo/skills,
 * github.com/callstackincubator/agent-skills.
 *
 * All items are opt-in; nothing here is enabled without `vectalon ecosystem
 * enable <id>` writing a .vectalon/ecosystem.json entry.
 */

const MCP_ITEMS: EcosystemItem[] = [
  {
    id: 'metro-mcp',
    category: 'mcp',
    name: 'Metro MCP',
    description: 'CDP-based runtime inspection for Metro/Hermes: console logs, network, component tree, Redux, UI automation, and test recording (Maestro/Detox/Appium).',
    flavor: 'both',
    url: 'https://github.com/steve228uk/metro-mcp',
    install: 'npx metro-mcp',
    capabilities: ['device', 'console logs', 'network', 'runtime errors', 'stack symbolication', 'AsyncStorage', 'components', 'redux', 'deeplink', 'permissions', 'filesystem', 'ui-interact', 'navigation', 'accessibility', 'test-recorder'],
    packageName: 'metro-mcp',
  },
  {
    id: 'expo-mcp',
    category: 'mcp',
    name: 'Expo MCP Server',
    description: 'Official Expo MCP: docs search, npx expo install for deps, EAS builds/workflows, TestFlight/Play Store data, and local expo-router sitemap + device logs.',
    flavor: 'expo',
    url: 'https://docs.expo.dev/mcp/',
    install: 'npx expo mcp',
    capabilities: ['search_documentation', 'read_documentation', 'learn', 'add_library', 'workflow_create', 'workflow_validate', 'workflow_run', 'workflow_logs', 'build_run', 'build_list', 'build_info', 'build_logs', 'build_submit', 'testflight_crashes', 'playstore_reviews', 'expo_router_sitemap', 'open_devtools', 'collect_app_logs', 'automation_tap'],
    packageName: 'expo-mcp',
  },
  {
    id: 'react-native-mcp',
    category: 'mcp',
    name: 'React Native MCP (ohah)',
    description: 'React Fiber tree + hook state inspection (useState/Zustand), re-render profiler, network mocking, and 49 automation tools via adb/idb.',
    flavor: 'both',
    url: 'https://github.com/ohah/react-native-mcp',
    // No dist-tag: the `rc` tag equals `latest` today and could vanish; npx
    // defaults to `latest` when none is given.
    install: 'npx @ohah/react-native-mcp-server',
    capabilities: ['inspect_fiber_tree', 'read_hook_state', 'track_rerenders', 'mock_network', 'tap', 'swipe', 'screenshot', 'assert', 'evaluate_script', 'ci_yaml'],
    packageName: '@ohah/react-native-mcp-server',
  },
  {
    id: 'react-native-guide-mcp',
    category: 'mcp',
    name: 'React Native Guide MCP',
    description: 'Code quality enforcement: auto-remediation (secrets → env, memory leaks), component refactoring (StyleSheet, FlatList), test generation, and dependency auditing.',
    flavor: 'both',
    url: 'https://github.com/MrNitro360/React-Native-MCP',
    install: 'npx @mrnitro360/react-native-mcp-guide',
    capabilities: ['remediate_code', 'refactor_component', 'generate_tests', 'check_coverage', 'check_accessibility', 'audit_dependencies'],
    packageName: '@mrnitro360/react-native-mcp-guide',
  },
  {
    id: 'react-native-upgrader-mcp',
    category: 'mcp',
    name: 'React Native Upgrader MCP',
    description: 'Track stable/RC RN versions and generate exact upgrade diffs (rn-diff-purge) with migration guidance.',
    flavor: 'rn-cli',
    url: 'https://github.com/patrickkabwe/react-native-upgrader-mcp',
    install: 'npx react-native-upgrader-mcp',
    capabilities: ['get-stable-version', 'get-rc-version', 'get-react-native-diff'],
    packageName: 'react-native-upgrader-mcp',
  },
]

const SKILL_ITEMS: EcosystemItem[] = [
  {
    id: 'expo-skills',
    category: 'skill',
    name: 'Expo Skills (all-in-one)',
    description: 'Bulk install of all official Expo agent skills: expo-router, native UI, data fetching, tailwind, dev-client, DOM, upgrade, EAS, and more.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill \'*\'',
    capabilities: ['expo-router', 'expo-native-ui', 'expo-ui', 'expo-data-fetching', 'expo-tailwind-setup', 'expo-dev-client', 'expo-module', 'expo-dom', 'expo-upgrade', 'expo-brownfield', 'expo-project-structure', 'expo-web-to-native', 'expo-app-clip', 'eas-app-stores', 'eas-hosting', 'eas-workflows', 'eas-observe', 'eas-update-insights', 'eas-simulator'],
    configPath: '.vectalon/skills/expo',
  },
  {
    id: 'expo-router',
    category: 'skill',
    name: 'Expo Router',
    description: 'File-based routing configuration: static/dynamic routes, native stacks, tabs, modals, deep linking, and typed routes.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-router',
    capabilities: ['file-based-routes', 'dynamic-paths', 'native-stacks', 'tabs', 'modals', 'deep-linking', 'typed-routes'],
    configPath: '.vectalon/skills/expo-router',
  },
  {
    id: 'expo-ui',
    category: 'skill',
    name: 'Expo UI / Native UI',
    description: 'Building native screens with @expo/ui (SwiftUI on iOS, Jetpack Compose on Android) and semantic styling controls.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-ui',
    capabilities: ['@expo/ui', 'native-components', 'semantic-colors', 'platform-styling', 'cross-platform-ui'],
    configPath: '.vectalon/skills/expo-ui',
  },
  {
    id: 'expo-tailwind-setup',
    category: 'skill',
    name: 'Expo Tailwind Setup',
    description: 'Configure NativeWind v5 with Tailwind CSS v4: Metro config, babel plugin, postcss, global CSS, and design tokens.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-tailwind-setup',
    capabilities: ['nativewind-v5', 'tailwind-v4', 'metro-config', 'babel-plugin', 'design-tokens', 'global-css'],
    configPath: '.vectalon/skills/expo-tailwind',
  },
  {
    id: 'expo-data-fetching',
    category: 'skill',
    name: 'Expo Data Fetching',
    description: 'Network architecture: TanStack Query, offline-first storage, caching strategies, and optimistic updates.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-data-fetching',
    capabilities: ['tanstack-query', 'offline-first', 'caching-strategies', 'optimistic-updates', 'network-architecture'],
    configPath: '.vectalon/skills/expo-data-fetching',
  },
  {
    id: 'expo-dev-client',
    category: 'skill',
    name: 'Expo Dev Client',
    description: 'Custom development builds for native code testing: build phases, native modules, and dev-launcher workflows.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-dev-client',
    capabilities: ['custom-dev-builds', 'native-code-testing', 'dev-launcher', 'build-phases', 'native-module-verification'],
    configPath: '.vectalon/skills/expo-dev-client',
  },
  {
    id: 'expo-dom',
    category: 'skill',
    name: 'Expo DOM',
    description: 'Embed web-only libraries natively using DOM components inside Expo apps.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-dom',
    capabilities: ['dom-components', 'web-library-embedding', 'native-web-bridge'],
    configPath: '.vectalon/skills/expo-dom',
  },
  {
    id: 'expo-upgrade',
    category: 'skill',
    name: 'Expo Upgrade',
    description: 'SDK version migrations: cache clearing, breaking-change codemods, dependency resolution, and post-upgrade validation.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-upgrade',
    capabilities: ['sdk-migration', 'cache-clearing', 'codemods', 'dependency-resolution', 'post-upgrade-validation'],
    configPath: '.vectalon/skills/expo-upgrade',
  },
  {
    id: 'expo-project-structure',
    category: 'skill',
    name: 'Expo Project Structure',
    description: 'Standards for file organization, app entry points, and configuration in Expo projects.',
    flavor: 'expo',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-project-structure',
    capabilities: ['file-organization', 'app-entry-points', 'expo-config', 'directory-structure'],
    configPath: '.vectalon/skills/expo-project-structure',
  },
  {
    id: 'expo-module',
    category: 'skill',
    name: 'Expo Module',
    description: 'Native module development using Swift, Kotlin, and C++ for the Expo Modules API — works in both Expo and bare RN-CLI projects.',
    flavor: 'both',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-module',
    capabilities: ['swift-module', 'kotlin-module', 'cpp-expo-module', 'expo-modules-api', 'native-bridge'],
    configPath: '.vectalon/skills/expo-module',
  },
  {
    id: 'expo-brownfield',
    category: 'skill',
    name: 'Expo Brownfield',
    description: 'Integrate React Native screens into pre-existing native Android (Java/Kotlin) or iOS (Swift/Obj-C) codebases using Expo SDK.',
    flavor: 'rn-cli',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill expo-brownfield',
    capabilities: ['xcframework-integration', 'aar-integration', 'ios-bridging', 'android-bridging', 'incremental-rn-adoption'],
    configPath: '.vectalon/skills/expo-brownfield',
  },
  {
    id: 'callstack-agent-skills',
    category: 'skill',
    name: 'Callstack Agent Skills',
    description: 'React Native best practices from Callstack: profiling, FlashList, React Compiler, Turbo Modules, R8, bundle size, plus upgrade and brownfield migration workflows.',
    flavor: 'both',
    url: 'https://github.com/callstackincubator/agent-skills',
    install: 'npx skills add callstackincubator/agent-skills --skill react-native-best-practices',
    capabilities: ['react-native-best-practices', 'upgrading-react-native', 'react-native-brownfield-migration', 'create-react-native-library', 'github-actions'],
    configPath: '.vectalon/skills/callstack',
  },
  {
    id: 'react-native-expert',
    category: 'skill',
    name: 'React Native Expert',
    description: 'Senior React Native/Expo engineering: platform handling, FlashList/LegendList performance, native thread management, Hermes profiling, and cross-platform architecture.',
    flavor: 'both',
    url: 'https://github.com/tech-leads-club/agent-skills',
    install: 'npx skills add tech-leads-club/agent-skills --skill react-native-expert',
    capabilities: ['platform-handling', 'flashlist-performance', 'legend-list', 'native-thread-mgmt', 'hermes-profiling', 'cross-platform-architecture', 'react-compiler', 'metro-bundle-size'],
    configPath: '.vectalon/skills/rn-expert',
  },
  {
    id: 'android-e2e-testing',
    category: 'skill',
    name: 'Android E2E Testing',
    description: 'Automate Android emulator workflows: ADB shell commands, UI Automator, emulator lifecycle, and screenshot testing.',
    flavor: 'both',
    url: 'https://github.com/expo/skills',
    install: 'npx skills@latest add expo/skills --skill android-e2e-testing',
    capabilities: ['adb-commands', 'ui-automator', 'emulator-lifecycle', 'screenshot-testing', 'android-debugging'],
    configPath: '.vectalon/skills/android-e2e',
  },
]

const SUPPORTING_TOOL_ITEMS: EcosystemItem[] = [
  {
    id: 'reactotron',
    category: 'tool',
    name: 'Reactotron',
    description: 'Desktop debugger for RN/Expo: inspect state, network requests, console logs, and dispatch actions in real-time.',
    flavor: 'both',
    url: 'https://github.com/infinitered/reactotron',
    install: 'npm install -D @reactotron/react-native',
    capabilities: ['state-inspection', 'network-logging', 'console-monitoring', 'action-dispatching', 'performance-profiling'],
    packageName: '@reactotron/react-native',
  },
  {
    id: 'flipper',
    category: 'tool',
    name: 'Flipper',
    description: 'Platform-agnostic debugger: layout inspector, network, database, crash reporter, and plugin system for RN.',
    flavor: 'rn-cli',
    url: 'https://github.com/facebook/flipper',
    install: 'npm install -D react-native-flipper',
    capabilities: ['layout-inspector', 'network-inspector', 'database-inspector', 'crash-reporter', 'plugin-system'],
    packageName: 'react-native-flipper',
  },
  {
    id: 'rn-devtools',
    category: 'tool',
    name: 'React Native DevTools',
    description: 'Official RN DevTools: component tree, React profiler, and source-level debugging for Hermes and JSC.',
    flavor: 'both',
    url: 'https://github.com/react-native-community/devtools',
    install: 'npm install -D @react-native/devtools',
    capabilities: ['component-tree', 'react-profiler', 'hermes-debugging', 'source-level-debugging', 'performance-timeline'],
    packageName: '@react-native/devtools',
  },
  {
    id: 'zustand',
    category: 'tool',
    name: 'Zustand',
    description: 'Small, fast state management with hooks — devtools, middleware, and storage persistence built in.',
    flavor: 'both',
    url: 'https://github.com/pmndrs/zustand',
    install: 'npm install zustand',
    capabilities: ['state-management', 'hooks-api', 'devtools-middleware', 'persist-middleware', 'immer-middleware'],
    packageName: 'zustand',
  },
  {
    id: 'mmkv',
    category: 'tool',
    name: 'MMKV',
    description: 'High-performance key-value storage (native C++): >30x faster than AsyncStorage, synchronous reads, encryption.',
    flavor: 'both',
    url: 'https://github.com/mrousavy/react-native-mmkv',
    install: 'npm install react-native-mmkv',
    capabilities: ['key-value-storage', 'synchronous-reads', 'encryption', 'high-performance', 'native-cpp'],
    packageName: 'react-native-mmkv',
  },
  {
    id: 'secure-store',
    category: 'tool',
    name: 'React Native SecureStore',
    description: 'Encrypted storage via Keychain (iOS) / EncryptedSharedPreferences (Android) for tokens, secrets, and credentials.',
    flavor: 'both',
    url: 'https://github.com/oblador/react-native-keychain',
    install: 'npm install react-native-keychain',
    capabilities: ['encrypted-storage', 'keychain', 'token-management', 'biometric-auth', 'secure-credentials'],
    packageName: 'react-native-keychain',
  },
  {
    id: 'reanimated',
    category: 'tool',
    name: 'React Native Reanimated',
    description: 'High-performance animations on the UI thread: worklets, shared values, animated props, and gesture-driven animations.',
    flavor: 'both',
    url: 'https://github.com/software-mansion/react-native-reanimated',
    install: 'npm install react-native-reanimated',
    capabilities: ['ui-thread-animations', 'worklets', 'shared-values', 'animated-props', 'gesture-animations', 'layout-animations'],
    packageName: 'react-native-reanimated',
  },
  {
    id: 'gesture-handler',
    category: 'tool',
    name: 'React Native Gesture Handler',
    description: 'Declarative gesture system: pan, pinch, rotation, tap, long-press, and native-thread gesture recognition.',
    flavor: 'both',
    url: 'https://github.com/software-mansion/react-native-gesture-handler',
    install: 'npm install react-native-gesture-handler',
    capabilities: ['pan-gesture', 'pinch-gesture', 'rotation-gesture', 'tap-gesture', 'long-press', 'native-thread-gestures'],
    packageName: 'react-native-gesture-handler',
  },
  {
    id: 'eas-cli',
    category: 'tool',
    name: 'EAS CLI',
    description: 'Expo Application Services CLI: build, submit, update, and manage EAS projects from the command line.',
    flavor: 'expo',
    url: 'https://docs.expo.dev/eas-cli/',
    install: 'npm install -g eas-cli',
    capabilities: ['eas-build', 'eas-submit', 'eas-update', 'eas-project-manage', 'eas-secrets'],
    packageName: 'eas-cli',
  },
  {
    id: 'fastlane',
    category: 'tool',
    name: 'Fastlane',
    description: 'Automate beta deployments and releases to the App Store and Google Play for bare RN-CLI projects.',
    flavor: 'rn-cli',
    url: 'https://github.com/fastlane/fastlane',
    install: 'gem install fastlane',
    capabilities: ['beta-deployment', 'app-store-connect', 'google-play-console', 'code-signing', 'screenshot-automation', 'match'],
  },
]

const TOOL_ITEMS: EcosystemItem[] = [
  {
    id: 'repomix',
    category: 'tool',
    name: 'Repomix',
    description: 'Pack the whole repo (JS + native ios/android layers) into one coherent markdown context file for LLM priming.',
    flavor: 'both',
    url: 'https://github.com/yamadashy/repomix',
    install: 'npx repomix',
    capabilities: ['repo-packing', 'context-priming', 'codebase-summary'],
    packageName: 'repomix',
  },
  {
    id: 'rn-diff-purge',
    category: 'tool',
    name: 'rn-diff-purge',
    description: 'Community-maintained diffs between every React Native CLI template release — the authoritative source for bare RN upgrades. Vectalon fetches them live (diffs/diffs/<from>..<to>.diff) and classifies native vs JS/TS changes. Not an npm package — browse diffs at the Upgrade Helper.',
    flavor: 'rn-cli',
    url: 'https://github.com/react-native-community/rn-diff-purge',
    install: 'https://react-native-community.github.io/upgrade-helper/',
    capabilities: ['upgrade-diffs', 'version-migration', 'native-template-diffs', 'js-ts-template-diffs'],
  },
  {
    id: 'maestro',
    category: 'tool',
    name: 'Maestro',
    description: 'YAML-based mobile UI testing (iOS + Android) — the simplest E2E option for generated RN apps.',
    flavor: 'both',
    url: 'https://github.com/mobile-dev-inc/Maestro',
    install: 'curl -Ls "https://get.maestro.mobile.dev" | bash',
    capabilities: ['ui-automation', 'yaml-flows', 'ios-android'],
  },
  {
    id: 'detox',
    category: 'tool',
    name: 'Detox',
    description: 'Gray-box E2E testing for RN with native synchronization (expo-dev-client compatible).',
    flavor: 'both',
    url: 'https://github.com/wix/Detox',
    install: 'npm install -D detox && npx detox init',
    capabilities: ['e2e-testing', 'native-sync', 'ci-ready'],
    packageName: 'detox',
  },
  {
    id: 'flashlist',
    category: 'tool',
    name: 'FlashList',
    description: 'Shopify\'s high-performance list — agents should prefer it over ScrollView maps for long lists.',
    flavor: 'both',
    url: 'https://github.com/Shopify/flash-list',
    install: 'npm install @shopify/flash-list',
    capabilities: ['virtualized-list', 'performance'],
    packageName: '@shopify/flash-list',
  },
  {
    id: 'expo-doctor',
    category: 'tool',
    name: 'expo-doctor',
    description: 'Check Expo project health: version alignment, config plugins, dependency compatibility.',
    flavor: 'expo',
    url: 'https://docs.expo.dev/more/expo-doctor/',
    install: 'npx expo-doctor',
    capabilities: ['health-check', 'version-alignment', 'config-validation'],
    packageName: 'expo-doctor',
  },
]

const HOOK_ITEMS: EcosystemItem[] = [
  {
    id: 'husky',
    category: 'hook',
    name: 'Husky',
    description: 'Git hooks for RN projects — run lint/typecheck/tests before commits so the harness\'s generated code never lands broken.',
    flavor: 'both',
    url: 'https://github.com/typicode/husky',
    install: 'npm install -D husky && npx husky init',
    capabilities: ['pre-commit', 'pre-push', 'lint-staged'],
    packageName: 'husky',
  },
  {
    id: 'lint-staged',
    category: 'hook',
    name: 'lint-staged',
    description: 'Run lint/format/typecheck only on staged files — fast pre-commit validation for generated code.',
    flavor: 'both',
    url: 'https://github.com/lint-staged/lint-staged',
    install: 'npm install -D lint-staged',
    capabilities: ['staged-lint', 'staged-format', 'pre-commit'],
    packageName: 'lint-staged',
  },
  {
    id: 'lefthook',
    category: 'hook',
    name: 'Lefthook',
    description: 'Fast, parallel git hooks manager (Go) — an alternative to husky with per-project parallel lint/typecheck.',
    flavor: 'both',
    url: 'https://github.com/evilmartians/lefthook',
    install: 'npm install -D lefthook && npx lefthook install',
    capabilities: ['pre-commit', 'parallel-jobs', 'pre-push'],
    packageName: 'lefthook',
  },
]

export const ECOSYSTEM_CATALOG: EcosystemCatalog = {
  version: '1.1.0',
  items: [...MCP_ITEMS, ...SKILL_ITEMS, ...TOOL_ITEMS, ...SUPPORTING_TOOL_ITEMS, ...HOOK_ITEMS],
}

export const ECOSYSTEM_ITEMS: EcosystemItem[] = ECOSYSTEM_CATALOG.items

export function getEcosystemItem(id: string): EcosystemItem | undefined {
  return ECOSYSTEM_ITEMS.find(i => i.id === id)
}

export function listEcosystemItems(filter?: { category?: string; flavor?: string }): EcosystemItem[] {
  return ECOSYSTEM_ITEMS.filter(i => {
    if (filter?.category && i.category !== filter.category) return false
    if (filter?.flavor && filter.flavor !== 'both' && i.flavor !== filter.flavor && i.flavor !== 'both') return false
    return true
  })
}
