import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { implementationPhase } from '../../src/workflows/phases/implementationPhase'
import { codeReviewPhase } from '../../src/workflows/phases/codeReviewPhase'
import { verificationPhase } from '../../src/workflows/phases/verificationPhase'
import { ModelRouter } from '../../src/model/ModelRouter'
import type { WorkflowContext } from '../../src/adapters/types'

// Intent always comes from the LLM, so the first generate() call is consumed
// by intent detection. These legacy tests were written before intent routing
// existed, so prepend an add-feature intent and let every subsequent call
// return the model response under test.
function createMockModelRouter(response: string): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  const mock = jest.spyOn(router, 'generate')
  mock.mockResolvedValueOnce({
    content: JSON.stringify({ intents: [{ type: 'add-feature', feature: 'login', confidence: 1, reasoning: 'new feature' }] }),
    provider: 'mock',
  })
  mock.mockResolvedValue({ content: response, provider: 'local' })
  return router
}

// Intent always comes from the LLM, so tests that exercise a specific intent
// must feed intent JSON to the first generate() call and the implementation
// response to subsequent calls.
function createMockModelRouterSequence(responses: string[]): ModelRouter {
  const router = new ModelRouter()
  router.initialize({ provider: 'local' })
  const mock = jest.spyOn(router, 'generate')
  for (const content of responses) {
    mock.mockResolvedValueOnce({ content, provider: 'mock' })
  }
  return router
}

function createContext(modelRouter: ModelRouter, prompt: string, projectRoot: string): WorkflowContext {
  return {
    projectRoot,
    snapshot: {
      project: {
        root: projectRoot,
        name: 'test-app',
        version: '1.0.0',
        reactNativeVersion: '0.72.0',
        dependencies: {},
        devDependencies: {},
        scripts: {},
        platforms: ['ios', 'android'],
        hasTypeScript: true,
        hasMetro: true,
        hasExpo: false,
        tooling: 'rn-cli',
        expoSdkVersion: '',
        reactVersion: '18.2.0',
      },
      structure: [],
      components: [],
      recentChanges: [],
      timestamp: Date.now(),
    },
    prompt,
    inputs: {},
    outputs: {},
    state: {
      id: 'test',
      workflowId: 'feature-development',
      prompt,
      status: 'running',
      phases: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    adapters: {
      projectManagement: { name: 'mock', createTasks: jest.fn(), updateTasks: jest.fn(), closeTasks: jest.fn(), readTicket: jest.fn(async () => null) },
      git: { name: 'mock', createBranch: jest.fn(), commit: jest.fn(), push: jest.fn(), createPullRequest: jest.fn(), commentPullRequest: jest.fn(), upsertPullRequestComment: jest.fn() },
      testRunner: { name: 'mock', runTests: jest.fn() },
      simulator: { name: 'mock', run: jest.fn() },
      design: { name: 'mock', analyzeMotion: jest.fn() },
    },
    modelRouter,
  }
}

describe('implementationPhase', () => {
  let tmpDir: string
  let projectRoot: string

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'vectalon-impl-'))
    projectRoot = tmpDir
  })

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true })
  })

  it('uses model-generated code when the model returns valid JSON', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
      notes: 'Generated by model',
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Generated by model')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBe('src/screens/AddLoginScreenScreen.tsx')
  })

  it('parses model output where file content is a backtick template literal (small-model failure mode)', async () => {
    // Qwen2.5-Coder and similar small models emit the JSON envelope with
    // `content` as a backtick template literal instead of a JSON string —
    // invalid JSON that used to score 0 files on the leaderboard. The repair
    // pass must recover the files.
    const response = [
      '```json',
      '{',
      '  "files": [',
      '    {',
      '      "path": "src/screens/AddLoginScreenScreen.tsx",',
      '      "content": `',
      '        import React from \'react\';',
      '        export function LoginScreen() { return null; }',
      '      `',
      '    }',
      '  ],',
      '  "notes": "A complete screen."',
      '}',
      '```',
    ].join('\n')
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBe('src/screens/AddLoginScreenScreen.tsx')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')
    expect(readFileSync(screenPath, 'utf-8')).toContain('export function LoginScreen')
  })

  it('writes model-generated JSON files to disk', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
    })
    const router = createMockModelRouter(response)
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')
    expect(readFileSync(screenPath, 'utf-8')).toContain('export function LoginScreen')
  })

  it('repairs a generated guardrail violation through Core before writing it', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'add-feature', feature: 'login', confidence: 1, reasoning: 'new feature' }] }),
      JSON.stringify({ files: [{ path: 'src/screens/Login.tsx', content: 'console.log("secret")\nexport function Login() { return null }' }] }),
      'export function Login() { return null }\n',
    ])

    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(readFileSync(join(projectRoot, 'src/screens/Login.tsx'), 'utf-8')).toBe('export function Login() { return null }\n')
    expect(result.artifacts[0].content).toBe('export function Login() { return null }\n')
    expect(jest.mocked(router.generate)).toHaveBeenCalledTimes(3)
  })

  it('does not write a generated file when Core exhausts repair', async () => {
    const invalid = 'console.log("still invalid")\nexport function Login() { return null }'
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'add-feature', feature: 'login', confidence: 1, reasoning: 'new feature' }] }),
      JSON.stringify({ files: [{ path: 'src/screens/InvalidLogin.tsx', content: invalid }] }),
      invalid,
    ])

    const context = createContext(router, 'Add a login screen', projectRoot)
    const result = await implementationPhase.run(context)

    expect(existsSync(join(projectRoot, 'src/screens/InvalidLogin.tsx'))).toBe(false)
    expect(result.output).toContain('Validation failed safely (REPAIR_EXHAUSTED)')
    expect(result.output).not.toContain('Files written to disk')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].path).toBeUndefined()
    expect(result.artifacts[0].content).not.toContain(invalid)

    context.state.phases.push(result)
    const review = await codeReviewPhase.run(context)
    context.state.phases.push(review)
    await verificationPhase.run(context)
    expect(existsSync(join(projectRoot, 'src/screens/InvalidLogin.tsx'))).toBe(false)
  })

  it('routes the deterministic fallback through Core and blocks invalid writes', async () => {
    mkdirSync(join(projectRoot, '.vectalon'), { recursive: true })
    writeFileSync(join(projectRoot, '.vectalon', 'policy.json'), JSON.stringify({
      version: 1,
      customRules: [{
        id: 'block-scaffold', name: 'Block scaffold', description: 'fixture rule',
        severity: 'error', pattern: 'export', message: 'blocked by project policy',
      }],
    }))
    const router = createMockModelRouter('not parseable as generated files')

    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(existsSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'))).toBe(false)
    expect(result.output).toContain('Validation failed safely (GUARDRAIL_BLOCKED)')
    expect(result.output).not.toContain('Files written to disk')
    expect(result.artifacts.every(artifact => artifact.path === undefined)).toBe(true)
    expect(result.artifacts.every(artifact => !artifact.content.includes('export class'))).toBe(true)
  })

  it('preserves the legacy guardrail summary for a no-project fallback', async () => {
    const router = createMockModelRouter('not parseable as generated files')
    const context = createContext(router, 'Add a login screen', projectRoot)
    context.projectRoot = undefined as never

    const result = await implementationPhase.run(context)

    expect(result.output).toContain('## Guardrail summary')
    expect(result.output).toContain('All guardrails passed')
  })

  it('parses markdown sections with ### paths and fenced code into files on disk', async () => {
    const response = [
      'Here are the files:',
      '',
      '### src/services/AddLoginScreenApi.ts',
      '```typescript',
      'export class AddLoginScreenApi { async execute() { return "ok" } }',
      '```',
      '',
      '### src/screens/AddLoginScreenScreen.tsx',
      '```tsx',
      'export function AddLoginScreenScreen() { return null }',
      '```',
    ].join('\n')
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts).toHaveLength(2)
    const servicePath = join(projectRoot, 'src/services/AddLoginScreenApi.ts')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')
    expect(readFileSync(servicePath, 'utf-8')).toContain('class AddLoginScreenApi')
    expect(readFileSync(screenPath, 'utf-8')).toContain('AddLoginScreenScreen')
    expect(result.output).toContain('Files written to disk')
  })

  it('parses bare path lines followed by fenced code blocks', async () => {
    const response = [
      'src/hooks/useAddLoginScreen.ts',
      '```ts',
      'export function useAddLoginScreen() { return { run: async () => "ok" } }',
      '```',
    ].join('\n')
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts).toHaveLength(1)
    const hookPath = join(projectRoot, 'src/hooks/useAddLoginScreen.ts')
    expect(readFileSync(hookPath, 'utf-8')).toContain('useAddLoginScreen')
  })

  it('preserves unparseable model output as a note instead of discarding it', async () => {
    const router = createMockModelRouter('the login screen should use email and password fields with validation')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Model output (not applied)')
    expect(result.output).toContain('email and password fields')
    // Still falls back to the deterministic scaffold so the phase produces runnable files
    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })

  it('rejects path traversal and absolute paths from model output', async () => {
    const response = JSON.stringify({
      files: [
        { path: '../evil.ts', content: 'export const evil = 1' },
        { path: '/etc/hosts.ts', content: 'export const hosts = 1' },
        { path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    // Safe file written; unsafe paths filtered out entirely
    expect(readFileSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'), 'utf-8')).toContain('LoginScreen')
    expect(result.artifacts.map(a => a.path)).toEqual(['src/screens/AddLoginScreenScreen.tsx'])
    expect(existsSync(join(projectRoot, '../evil.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'etc/hosts.ts'))).toBe(false)
  })

  it('drops JSON entries that lack string content', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/services/AddLoginScreenApi.ts', content: 'export class AddLoginScreenApi {}' },
        { path: 'src/hooks/useAddLoginScreen.ts' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.artifacts.map(a => a.path)).toEqual(['src/services/AddLoginScreenApi.ts'])
    expect(readFileSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'), 'utf-8')).toContain('AddLoginScreenApi')
  })

  it('keeps generated scaffold out of src/ when the project is the rn-vectalon package itself', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: '@vectalon-dev/rn', version: '0.5.0' }))

    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('.vectalon/generated')
    // Nothing written into the package's own src/
    expect(existsSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/hooks/useAddLoginScreen.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'))).toBe(false)
    // Generated files land in the gitignored output dir instead
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/services/AddLoginScreenApi.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/hooks/useAddLoginScreen.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/screens/AddLoginScreenScreen.tsx'))).toBe(true)
  })

  it('keeps model-generated files out of src/ when the project is the rn-vectalon package itself', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: '@vectalon-dev/rn', version: '0.5.0' }))
    const response = JSON.stringify({
      files: [{ path: 'src/screens/AddLoginScreenScreen.tsx', content: 'export function LoginScreen() { return null }' }],
    })
    const router = createMockModelRouter(response)
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(existsSync(join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx'))).toBe(false)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/screens/AddLoginScreenScreen.tsx'))).toBe(true)
  })

  it('still writes into src/ for a regular React Native project', async () => {
    writeFileSync(join(projectRoot, 'package.json'), JSON.stringify({ name: 'my-app', version: '1.0.0' }))

    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(existsSync(join(projectRoot, 'src/services/AddLoginScreenApi.ts'))).toBe(true)
    expect(existsSync(join(projectRoot, '.vectalon/generated/src/services/AddLoginScreenApi.ts'))).toBe(false)
    expect(result.output).not.toContain('.vectalon/generated')
  })

  it('falls back to deterministic scaffold when the model returns fallback marker', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
    expect(result.output).toContain('src/hooks/useAddLoginScreen.ts')
    expect(result.output).toContain('src/screens/AddLoginScreenScreen.tsx')
    expect(result.output).toContain('Files written to disk')
  })

  it('falls back to deterministic scaffold when the model returns unparseable JSON', async () => {
    const router = createMockModelRouter('some plain text without json')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('src/services/AddLoginScreenApi.ts')
  })

  it('writes generated scaffold files to disk for add-feature', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    const servicePath = join(projectRoot, 'src/services/AddLoginScreenApi.ts')
    const hookPath = join(projectRoot, 'src/hooks/useAddLoginScreen.ts')
    const screenPath = join(projectRoot, 'src/screens/AddLoginScreenScreen.tsx')

    expect(readFileSync(servicePath, 'utf-8')).toContain('class AddLoginScreenApi')
    expect(readFileSync(hookPath, 'utf-8')).toContain('useAddLoginScreen')
    expect(readFileSync(screenPath, 'utf-8')).toContain('AddLoginScreenScreen')
  })

  it('removes unused imports when the intent is refactor remove-unused-imports', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    const filePath = join(srcDir, 'Example.tsx')
    writeFileSync(
      filePath,
      [
        "import React from 'react';",
        "import { View, Text } from 'react-native';",
        "import { unusedHelper } from './helpers';",
        '',
        'export function Example() {',
        '  return <View><Text>Hi</Text></View>;',
        '}',
      ].join('\n')
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'refactor', target: 'remove-unused-imports', confidence: 1, reasoning: 'unused imports to remove' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'remove unused imports throughout the app', projectRoot))

    expect(result.output).toContain('Refactor: remove unused imports')
    expect(result.output).toContain('Files modified')
    expect(result.output).toContain(filePath)

    const updated = readFileSync(filePath, 'utf-8')
    expect(updated).toContain("import { View, Text } from 'react-native';")
    expect(updated).not.toContain("import { unusedHelper } from './helpers';")
  })

  it('reports guardrail summary for generated scaffold', async () => {
    const router = createMockModelRouter('[Local model fallback: no downloaded model]')
    const result = await implementationPhase.run(createContext(router, 'Add a login screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('All guardrails passed')
  })

  it('reports guardrail findings for model-generated code with violations', async () => {
    const response = JSON.stringify({
      files: [
        { path: 'src/screens/BadScreen.tsx', content: 'export function BadScreen() { console.log("hi"); return null; }' },
      ],
    })
    const router = createMockModelRouter(response)
    const result = await implementationPhase.run(createContext(router, 'Add a bad screen', projectRoot))

    expect(result.output).toContain('Guardrail summary')
    expect(result.output).toContain('No console.log statements')
    expect(result.output).toContain('1 error(s)')
  })

  it('routes lint-fix requests to the fix path and repairs existing files without scaffolding', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
      JSON.stringify({
        files: [
          { path: 'src/screens/Home.tsx', content: 'export function Home() { return null }' },
        ],
      }),
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: false,
        stdout: '',
        stderr: 'src/screens/Home.tsx:3:5 - Unexpected console statement (no-console)',
        exitCode: 1,
      }),
    }

    const result = await implementationPhase.run(ctx)

    // The repaired file was written to disk
    expect(result.artifacts.map(a => a.path)).toEqual(['src/screens/Home.tsx'])
    expect(readFileSync(join(projectRoot, 'src/screens/Home.tsx'), 'utf-8')).toContain('export function Home')
    // No scaffold files were created for the request
    expect(existsSync(join(projectRoot, 'src/services/FixAllLintIssuesApi.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/hooks/useFixAllLintIssues.ts'))).toBe(false)
    expect(existsSync(join(projectRoot, 'src/screens/FixAllLintIssuesScreen.tsx'))).toBe(false)
  })

  it('never scaffolds new files for a lint-fix request when the model cannot produce a fix', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
      'this model output cannot be parsed into files',
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: false,
        stdout: '',
        stderr: 'src/screens/Home.tsx:3:5 - Unexpected console statement (no-console)',
        exitCode: 1,
      }),
    }

    const result = await implementationPhase.run(ctx)

    expect(result.output).toContain('Fix lint issues')
    expect(result.output).toContain('No files were created or modified')
    expect(result.output).toContain('no-console')
    // Nothing was written to disk at all
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
  })

  it('reports a clean check for a lint-fix request when lint already passes', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'fix', area: 'lint', confidence: 1, reasoning: 'lint violations' }] }),
    ])
    const ctx = createContext(router, 'fix all lint issues', projectRoot)
    ctx.adapters.testRunner = {
      name: 'mock',
      runTests: jest.fn(),
      runLint: jest.fn().mockResolvedValue({
        success: true,
        stdout: 'No lint issues',
        stderr: '',
        exitCode: 0,
      }),
    }

    const result = await implementationPhase.run(ctx)

    expect(result.output).toContain('passes cleanly')
    expect(result.output).toContain('Nothing to fix')
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
  })

  it('removes a dependency from package.json and strips its imports from source files', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    writeFileSync(
      join(projectRoot, 'package.json'),
      JSON.stringify(
        {
          name: 'my-app',
          version: '1.0.0',
          dependencies: {
            'react-native': '0.72.0',
            appcenter: '4.4.5',
            'appcenter-analytics': '4.4.5',
            'appcenter-crashes': '4.4.5',
            'appcenter-push': '4.4.5',
          },
        },
        null,
        2
      )
    )
    writeFileSync(
      join(srcDir, 'App.tsx'),
      [
        "import React from 'react';",
        "import AppCenter from 'appcenter';",
        "import { AppCenterAnalytics } from 'appcenter-analytics';",
        "const { AppCenterCrashes } = require('appcenter-crashes');",
        "export { AppCenterPush } from 'appcenter-push';",
        '',
        'export function App() { return null }',
      ].join('\n')
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'remove-dependency', dependency: 'appcenter', confidence: 1, reasoning: 'remove appcenter' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'Remove appcenter safely from this project', projectRoot))

    // package.json edited on disk — the dependency is gone, unrelated deps stay.
    const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf-8'))
    expect(pkg.dependencies).not.toHaveProperty('appcenter')
    expect(pkg.dependencies).not.toHaveProperty('appcenter-analytics')
    expect(pkg.dependencies).toHaveProperty('react-native')

    // Source imports stripped (including destructured require + re-exports).
    const app = readFileSync(join(srcDir, 'App.tsx'), 'utf-8')
    expect(app).not.toContain("from 'appcenter'")
    expect(app).not.toContain('require(')
    expect(app).not.toContain('appcenter-push')
    expect(app).toContain('export function App()')

    expect(result.output).toContain('Remove dependency: appcenter')
    expect(result.output).toContain('Changes applied')
    expect(result.output).toContain('package.json: removed appcenter, appcenter-analytics')
    expect(result.output).toContain('src/App.tsx: stripped appcenter import(s)')
    expect(existsSync(join(projectRoot, 'scripts/remove-appcenter.sh'))).toBe(true)
  })

  it('strips iOS/Android native references (pods, gradle includes, imports) when removing a dependency', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    writeFileSync(
      join(projectRoot, 'package.json'),
      JSON.stringify(
        { name: 'my-app', version: '1.0.0', dependencies: { 'react-native': '0.72.0', appcenter: '5.0.3' } },
        null,
        2
      )
    )
    mkdirSync(join(projectRoot, 'ios'), { recursive: true })
    mkdirSync(join(projectRoot, 'android/app/src/main/java/com/app'), { recursive: true })
    writeFileSync(
      join(projectRoot, 'ios/Podfile'),
      [
        "require_relative '../node_modules/react-native/scripts/react_native_pods'",
        "pod 'AppCenter', :path => '../node_modules/appcenter/ios'",
        "pod 'React', :path => '../node_modules/react-native/ReactCommon'",
      ].join('\n')
    )
    writeFileSync(
      join(projectRoot, 'android/settings.gradle'),
      [
        "include ':app'",
        "include ':appcenter'",
        "project(':appcenter').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter/android')",
      ].join('\n')
    )
    writeFileSync(
      join(projectRoot, 'android/app/src/main/java/com/app/MainApplication.kt'),
      [
        'import com.microsoft.appcenter.AppCenter',
        'import com.microsoft.appcenter.analytics.Analytics',
        '',
        'class MainApplication : Application() {',
        '  override fun onCreate() {',
        '    AppCenter.start(applicationContext, "secret", Analytics::class.java)',
        '  }',
        '}',
      ].join('\n')
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'remove-dependency', dependency: 'appcenter', confidence: 1, reasoning: 'remove appcenter' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'Remove appcenter safely from this project', projectRoot))

    // Podfile: pod declaration removed, unrelated pod untouched.
    const podfile = readFileSync(join(projectRoot, 'ios/Podfile'), 'utf-8')
    expect(podfile).not.toContain('AppCenter')
    expect(podfile).toContain("pod 'React'")

    // settings.gradle: include + projectDir removed, app include untouched.
    const settings = readFileSync(join(projectRoot, 'android/settings.gradle'), 'utf-8')
    expect(settings).not.toContain('appcenter')
    expect(settings).toContain("include ':app'")

    // MainApplication: import lines removed, runtime usage reported (not deleted).
    const mainApplication = readFileSync(join(projectRoot, 'android/app/src/main/java/com/app/MainApplication.kt'), 'utf-8')
    expect(mainApplication).not.toContain('import com.microsoft.appcenter')
    expect(mainApplication).toContain('AppCenter.start')

    // Output surfaces the native work.
    expect(result.output).toContain('Native changes applied')
    expect(result.output).toContain('ios/Podfile')
    expect(result.output).toContain('android/settings.gradle')
    expect(result.output).toContain('Native references remaining')
  })

  it('reports dead native configuration for a remove-unused-native-config refactor (advisory, no edits)', async () => {
    mkdirSync(join(projectRoot, 'ios/MyApp'), { recursive: true })
    mkdirSync(join(projectRoot, 'android/app/src/main/java/com/app'), { recursive: true })
    writeFileSync(
      join(projectRoot, 'package.json'),
      JSON.stringify({ name: 'my-app', version: '1.0.0', dependencies: { 'react-native': '0.72.0' } }, null, 2)
    )
    writeFileSync(
      join(projectRoot, 'ios/Podfile'),
      [
        "pod 'AppCenter'",
        "pod 'React', :path => '../node_modules/react-native/ReactCommon'",
      ].join('\n')
    )
    writeFileSync(
      join(projectRoot, 'ios/MyApp/AppDelegate.mm'),
      '@implementation AppDelegate\n@end\n'
    )
    writeFileSync(
      join(projectRoot, 'android/settings.gradle'),
      "include ':app'\ninclude ':react-native-gone'\nproject(':react-native-gone').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gone/android')\n"
    )
    writeFileSync(
      join(projectRoot, 'android/app/build.gradle'),
      "dependencies {\n  implementation 'com.example:ghostlib:1.0.0'\n}\n"
    )
    writeFileSync(
      join(projectRoot, 'android/app/src/main/java/com/app/Thing.kt'),
      'import com.acme.ghost.Ghost\nclass Thing {}\n'
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'refactor', target: 'remove-unused-native-config', confidence: 1, reasoning: 'dead native config' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'remove unused native config from the project', projectRoot))

    expect(result.output).toContain('Refactor: remove unused native config')
    expect(result.output).toContain('Findings (4)')
    expect(result.output).toContain('iOS — dead pods')
    expect(result.output).toContain('ios/Podfile')
    expect(result.output).toContain('Android — dead gradle includes')
    expect(result.output).toContain('android/settings.gradle')
    expect(result.output).toContain('Android — dead gradle dependencies')
    expect(result.output).toContain('Android — unused imports')
    expect(result.output).toContain('Advisory only — nothing was deleted')
    expect(result.artifacts[0].title).toBe('Dead native config report')
    // Nothing was written or modified.
    const podfile = readFileSync(join(projectRoot, 'ios/Podfile'), 'utf-8')
    expect(podfile).toContain("pod 'AppCenter'")
    expect(existsSync(join(projectRoot, 'scripts'))).toBe(false)
  })

  it('reports a clean dead-native-config scan when nothing is dead (no findings)', async () => {
    writeFileSync(
      join(projectRoot, 'package.json'),
      JSON.stringify({ name: 'my-app', version: '1.0.0', dependencies: { 'react-native': '0.72.0' } }, null, 2)
    )
    mkdirSync(join(projectRoot, 'ios'), { recursive: true })
    writeFileSync(
      join(projectRoot, 'ios/Podfile'),
      "pod 'React', :path => '../node_modules/react-native/ReactCommon'\n"
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'refactor', target: 'remove-unused-native-config', confidence: 1, reasoning: 'dead native config' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'remove unused native config', projectRoot))

    expect(result.output).toContain('Refactor: remove unused native config')
    expect(result.output).toContain('No candidate dead native configuration found')
    expect(result.artifacts).toHaveLength(1)
    expect(result.artifacts[0].title).toBe('Dead native config report')
  })

  it('asks the model to clean remaining usages after stripping imports', async () => {
    const srcDir = join(projectRoot, 'src')
    mkdirSync(srcDir, { recursive: true })
    writeFileSync(
      join(srcDir, 'index.ts'),
      [
        "import AppCenter from 'appcenter';",
        '',
        'export function start() {',
        "  AppCenter.startWithAppCenterSecret('secret');",
        '}',
      ].join('\n')
    )

    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'remove-dependency', dependency: 'appcenter', confidence: 1, reasoning: 'remove appcenter' }] }),
      JSON.stringify({ files: [{ path: 'src/index.ts', content: 'export function start() {\n  // analytics setup removed\n}' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'Remove appcenter from this project', projectRoot))

    const updated = readFileSync(join(srcDir, 'index.ts'), 'utf-8')
    expect(updated).not.toContain('AppCenter')
    expect(result.output).toContain('model removed remaining appcenter usage')
    expect(result.output).toContain('None — no non-import references remain')
  })

  it('produces a clarification plan and writes NO files when the intent is unknown', async () => {
    const router = createMockModelRouterSequence([
      JSON.stringify({ intents: [{ type: 'unknown', confidence: 0.5, reasoning: 'not sure' }] }),
    ])
    const result = await implementationPhase.run(createContext(router, 'Remove appcenter safely from this project', projectRoot))

    expect(result.output).toContain('Request not classified')
    expect(result.output).toContain('no files were created or modified')
    // Nothing was written to disk at all
    expect(existsSync(join(projectRoot, 'src'))).toBe(false)
    // No scaffold artifacts for the unknown request
    expect(result.artifacts.filter(a => a.type === 'engineering')).toHaveLength(1)
    expect(result.artifacts[0].title).toBe('Clarification needed')
  })
})
