import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, relative, extname } from 'path'
import { reportPathChange } from './fileDiff'
import { reportError } from './safe'

export type NativePlatform = 'ios' | 'android'

export type NativeReferenceKind =
  | 'pod'       // Podfile `pod 'X'` declaration
  | 'pod-lock'  // Podfile.lock entry (regenerated by pod install)
  | 'gradle'    // settings.gradle include / build.gradle project() or maven dep
  | 'import'    // #import / import statement in native source
  | 'code'      // runtime usage (AppCenter.start(...), MainApplication wiring)
  | 'manifest'  // AndroidManifest.xml provider/activity
  | 'plist'     // Info.plist keys
  | 'pbxproj'   // Xcode project file (script phases, paths)

export interface NativeReference {
  platform: NativePlatform
  file: string // relative to project root
  line: number
  text: string
  kind: NativeReferenceKind
}

const SKIP_DIRS = new Set([
  'node_modules', 'build', '.gradle', '.cxx', 'Pods', 'DerivedData',
  'xcuserdata', '.git', '.expo', 'vendor', 'coverage', 'dist',
])

const RELEVANT_EXT = new Set([
  '.gradle', '.kts', '.pbxproj', '.plist', '.mm', '.m', '.h', '.swift',
  '.kt', '.java', '.xml', '.properties', '.podspec', '.xcconfig',
])

const RELEVANT_NAMES = new Set(['Podfile', 'Podfile.lock'])

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Name tokens that could reference a native package: the raw name (for
 * node_modules paths and gradle includes), the lowercased concatenation
 * (`appcenteranalytics`), and PascalCase (`AppCenter`, `AppCenterAnalytics`),
 * plus the scoped name for `@scope/name` path matches.
 *
 * For scoped packages (`@sentry/react-native`, `@react-native-firebase/app`)
 * the last segment is `react-native` or `app` — nearly meaningless — so the
 * identity lives in the SCOPE: `sentry`, `react-native-firebase` (→ `firebase`).
 * Tokens are derived from the scope and the full scoped name so native traces
 * like `RNSentry`, `io.sentry.android`, `:react-native-sentry`, and
 * `com.google.firebase.provider` are all caught.
 */
export function nativePackageTokens(pkg: string): string[] {
  const base = pkg.split('/').pop() || pkg
  const isScoped = pkg.startsWith('@')
  // Identity-bearing name: the scope for scoped packages, the base otherwise.
  const identity = isScoped ? pkg.slice(1) : base // 'sentry/react-native' | 'appcenter-analytics'
  const scope = isScoped ? identity.split('/')[0] : '' // 'sentry' | 'react-native-firebase'
  const stripped = (isScoped ? scope : base).replace(/^react-native-?/i, '') || (isScoped ? scope : base)
  const parts = identity.split(/[^a-zA-Z0-9]+/).filter(Boolean)
  const pascal = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  const strippedPascal = stripped.split(/[^a-zA-Z0-9]+/).filter(Boolean).map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  const tokens = new Set<string>([
    pkg,                    // full scoped name, e.g. @sentry/react-native
    base,                   // react-native | appcenter-analytics
    base.replace(/-/g, ''), // reactnative | appcenteranalytics
    parts.join('').toLowerCase(),
    pascal,                 // SentryReactNative | AppCenterAnalytics
    stripped,               // sentry | firebase | appcenter-analytics
    strippedPascal,         // Sentry | Firebase | AppcenterAnalytics
    scope,                  // sentry | react-native-firebase
    scope.replace(/-/g, ''),
  ])
  // A bare `react-native` / `ReactNative` token would false-positive on every
  // unrelated `node_modules/react-native-*` pod/gradle path when removing a
  // `react-native`-suffixed package (e.g. @sentry/react-native). The full scoped
  // name token already covers the real path match, so drop the ambiguous ones.
  tokens.delete('react-native')
  tokens.delete('ReactNative')
  tokens.delete('reactnative')
  // Short tokens (App from `app`) match AppDelegate/application classes
  // everywhere — require at least 4 characters to avoid false positives.
  return [...tokens].filter(t => t.length >= 4)
}

/**
 * True when a single line references any of the package tokens (Podfile pods,
 * gradle includes/deps, native imports, manifest providers, plist keys).
 * PascalCase tokens match on a start boundary so `AppCenter` catches
 * `AppCenter.start`, `AppCenterSecret`, and `AppCenterAnalytics`; lowercase
 * tokens match on full word boundaries so `appcenter` catches
 * `com.microsoft.appcenter.utils` but not `appcenterfoo`.
 */
export function isReferenceLine(line: string, tokens: string[]): boolean {
  for (const token of tokens) {
    const escaped = escapeRegExp(token)
    if (/^[A-Z]/.test(token)) {
      // PascalCase identifiers (AppCenter): start-boundary only, so
      // AppCenter matches AppCenter.start / AppCenterSecret / AppCenterAnalytics.
      const re = new RegExp(`(^|[^A-Za-z0-9])${escaped}`, 'i')
      if (re.test(line)) return true
    } else {
      // Lowercase tokens: full word boundary so `appcenter` matches
      // `com.microsoft.appcenter.utils` but not `appcenterfoo` / `okhttp3`
      // (a different Maven group than `okhttp`).
      const re = new RegExp(`(^|[^A-Za-z0-9])${escaped}([^A-Za-z0-9]|$)`, 'i')
      if (re.test(line)) return true
    }
  }
  return false
}

function classifyKind(file: string, line: string): NativeReferenceKind {
  const base = file.split('/').pop() || file
  const ext = extname(base).toLowerCase()
  if (base === 'Podfile') return 'pod'
  if (base === 'Podfile.lock') return 'pod-lock'
  if (ext === '.pbxproj') return 'pbxproj'
  if (ext === '.plist') return 'plist'
  if (base === 'AndroidManifest.xml') return 'manifest'
  if (ext === '.gradle' || ext === '.kts') return 'gradle'
  if (['.mm', '.m', '.h', '.swift', '.kt', '.java'].includes(ext)) {
    return /^\s*#?import\b/.test(line) ? 'import' : 'code'
  }
  return 'code'
}

function walkNativeDirs(
  root: string,
  platform: NativePlatform,
  out: { file: string; platform: NativePlatform }[]
): void {
  if (!existsSync(root)) return
  const stack = [root]
  while (stack.length > 0) {
    const dir = stack.pop() as string
    let entries: string[]
    try {
      entries = readdirSync(dir)
    } catch (err) {
      reportError(err, 'nativeScan: reading directory entries')
      continue
    }
    for (const entry of entries) {
      const full = join(dir, entry)
      let stat
      try {
        stat = statSync(full)
      } catch (err) {
        reportError(err, 'nativeScan: statting native file')
        continue
      }
      if (stat.isDirectory()) {
        if (!SKIP_DIRS.has(entry)) stack.push(full)
      } else if (RELEVANT_NAMES.has(entry) || RELEVANT_EXT.has(extname(entry).toLowerCase())) {
        out.push({ file: full, platform })
      }
    }
  }
}

/**
 * Scan the native ios/ and android/ trees for any line that references one of
 * the given packages (pod declarations, gradle includes/deps, native imports,
 * runtime usages, manifest/plist/pbxproj entries).
 */
export function scanNativeReferences(
  projectRoot: string,
  packageNames: string[]
): NativeReference[] {
  const refs: NativeReference[] = []
  const tokens = packageNames.flatMap(nativePackageTokens)
  const candidates: { file: string; platform: NativePlatform }[] = []
  walkNativeDirs(join(projectRoot, 'ios'), 'ios', candidates)
  walkNativeDirs(join(projectRoot, 'android'), 'android', candidates)

  for (const { file, platform } of candidates) {
    let content: string
    try {
      content = readFileSync(file, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading native candidate file')
      continue
    }
    const rel = relative(projectRoot, file)
    content.split('\n').forEach((line, idx) => {
      const trimmed = line.trim()
      if (!trimmed || /^(?:\/\/|\*|\/\*|#\s*!)/.test(trimmed)) return
      if (isReferenceLine(line, tokens)) {
        refs.push({
          platform,
          file: rel,
          line: idx + 1,
          text: trimmed.slice(0, 140),
          kind: classifyKind(rel, line),
        })
      }
    })
  }
  return refs
}

function isStrippable(ref: NativeReference, tokens: string[]): boolean {
  switch (ref.kind) {
    case 'pod': {
      // `pod 'AppCenter'` or `pod 'AppCenter', :path => '../node_modules/appcenter/ios'`
      const podName = ref.text.match(/pod\s+['"]([^'"]+)['"]/)
      if (podName && isReferenceLine(podName[1], tokens)) return true
      return /node_modules\//.test(ref.text) && isReferenceLine(ref.text, tokens)
    }
    case 'pod-lock': {
      // `- AppCenter (5.0.3)` / `- AppCenter/...` / `- AppCenter (from `../node_modules/...`)`
      if (/^-\s/.test(ref.text)) return true
      return /node_modules\//.test(ref.text)
    }
    case 'gradle': {
      // `include ':appcenter'`, `project(':appcenter').projectDir = ...`,
      // `implementation project(':appcenter')`, `implementation 'com.x:appcenter:5.0.3'`
      if (/include\s+['"]:?/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      if (/project\(\s*['"]:?/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      if (/^\s*(implementation|api|compile|testImplementation|debugImplementation|releaseImplementation)\b/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      return false
    }
    case 'import': {
      // `#import <AppCenter/AppCenter.h>` / `import com.microsoft.appcenter...`
      return /^\s*#?import\b/.test(ref.text) && isReferenceLine(ref.text, tokens)
    }
    default:
      // code usages, manifest providers, plist keys, pbxproj paths — reported,
      // never silently deleted (removing them can corrupt the build).
      return false
  }
}

export interface NativeStripResult {
  removed: NativeReference[]
  remaining: NativeReference[]
}

/**
 * Deterministically remove the safe, well-understood native references
 * (pod declarations, lockfile entries, gradle includes/project deps, native
 * import statements) from the project's ios/ and android/ trees. Everything
 * else — runtime usages, manifest/plist/pbxproj entries — is returned as
 * `remaining` for the caller to report (and optionally hand to the model).
 */
export function stripNativeReferences(
  projectRoot: string,
  packageNames: string[]
): NativeStripResult {
  const refs = scanNativeReferences(projectRoot, packageNames)
  const tokens = packageNames.flatMap(nativePackageTokens)
  const removed: NativeReference[] = []
  const remaining: NativeReference[] = []

  const toRemoveByFile = new Map<string, Set<number>>()
  for (const ref of refs) {
    if (isStrippable(ref, tokens)) {
      removed.push(ref)
      if (!toRemoveByFile.has(ref.file)) toRemoveByFile.set(ref.file, new Set())
      toRemoveByFile.get(ref.file)!.add(ref.line)
    } else {
      remaining.push(ref)
    }
  }

  for (const [rel, lineNums] of toRemoveByFile) {
    const full = join(projectRoot, rel)
    let original: string
    try {
      original = readFileSync(full, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading file to strip native references')
      continue
    }
    const kept = original
      .split('\n')
      .filter((_, idx) => !lineNums.has(idx + 1))
      .join('\n')
    if (kept !== original) {
      writeFileSync(full, kept, 'utf-8')
      reportPathChange(rel, original, kept)
    }
  }

  return { removed, remaining }
}

// ---------------------------------------------------------------------------
// Dead native configuration scan ("remove unused native config" refactor)
// ---------------------------------------------------------------------------

export type DeadNativeKind = 'pod' | 'gradle-include' | 'gradle-dep' | 'import'

export interface DeadNativeConfig {
  platform: NativePlatform
  file: string
  line: number
  kind: DeadNativeKind
  text: string
  reasoning: string
}

export interface DeadNativeScanResult {
  findings: DeadNativeConfig[]
  scannedFiles: number
}

const UNUSED_NATIVE_TARGET_RE = /(unused|dead|orphan|dangling|leftover|stale|redundant)/
const NATIVE_TARGET_RE = /(native|pod|gradle|maven|ios|android)/

/**
 * True when a refactor `target` asks for dead native config cleanup — e.g.
 * "remove unused native config", "remove dead pods", "clean up unused gradle
 * dependencies". Canonical spellings match exactly; anything else needs an
 * unused/dead-ish word AND a native-ish word, so generic refactors ("clean up
 * the home screen") never route here.
 */
export function isRemoveUnusedNativeConfigTarget(target: string): boolean {
  const t = target.toLowerCase().trim()
  if (!t) return false
  const canonical = new Set([
    'remove-unused-native-config',
    'remove-unused-native',
    'unused-native-config',
    'dead-native-config',
    'clean-native-config',
    'remove-dead-native-config',
  ])
  if (canonical.has(t)) return true
  return UNUSED_NATIVE_TARGET_RE.test(t) && NATIVE_TARGET_RE.test(t)
}

interface InstalledDependency {
  name: string
  version: string
}

function readInstalledDependencies(projectRoot: string): InstalledDependency[] {
  try {
    const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf-8')) as Record<string, Record<string, unknown>>
    const out: InstalledDependency[] = []
    for (const section of ['dependencies', 'devDependencies', 'optionalDependencies', 'peerDependencies']) {
      for (const [name, version] of Object.entries(pkg[section] || {})) {
        out.push({ name, version: String(version) })
      }
    }
    return out
  } catch (err) {
    reportError(err, 'nativeScan: parsing package.json for installed dependencies')
    return []
  }
}

function isInstalled(deps: InstalledDependency[], name: string): boolean {
  const n = name.toLowerCase()
  return deps.some(d => d.name.toLowerCase() === n)
}

interface PodfilePod {
  name: string
  line: number
  raw: string
  nodeModulesPath?: string
}

function parsePodfile(content: string): PodfilePod[] {
  const pods: PodfilePod[] = []
  const re = /pod\s+['"]([^'"]+)['"]\s*(?:,\s*([^\n]*))?/g
  let match: RegExpExecArray | null
  while ((match = re.exec(content)) !== null) {
    const nodeModulesPath = (match[2] || '').match(/:path\s*=>\s*['"]([^'"]*node_modules[^'"]*)['"]/)?.[1]
    const line = content.slice(0, match.index).split('\n').length
    pods.push({ name: match[1], line, raw: match[0].trim(), nodeModulesPath })
  }
  return pods
}

/** `../node_modules/@sentry/react-native/ios` -> `@sentry/react-native` */
function packageFromNodeModulesPath(path: string): string | null {
  const m = path.match(/node_modules\/(@[^/]+\/[^/]+|[^/]+)/)
  return m ? m[1] : null
}

function contentReferencesTokens(content: string, tokens: string[]): boolean {
  return content.split('\n').some(line => isReferenceLine(line, tokens))
}

/**
 * Case-insensitive substring match — used for the dead-config scan where
 * usage often embeds the module name mid-identifier (MSACAppCenter uses
 * AppCenter, okhttp3 uses okhttp). Boundary matching would false-positive.
 */
function contentMentionsToken(content: string, token: string): boolean {
  return token.length > 0 && content.toLowerCase().includes(token.toLowerCase())
}

/**
 * iOS-only: does any native source file (excluding Podfile / Podfile.lock)
 * reference the given tokens? Used to decide whether a Podfile pod is dead.
 */
function iosNativeFilesReference(root: string, tokens: string[]): boolean {
  const candidates: { file: string; platform: NativePlatform }[] = []
  walkNativeDirs(join(root, 'ios'), 'ios', candidates)
  for (const { file } of candidates) {
    const base = file.split('/').pop() || file
    if (base === 'Podfile' || base === 'Podfile.lock') continue
    try {
      const content = readFileSync(file, 'utf-8')
      if (tokens.some(t => contentMentionsToken(content, t))) return true
    } catch (err) {
      reportError(err, 'nativeScan: reading iOS file while checking pod usage')
    }
  }
  return false
}

const LOCAL_HEADER_IMPORT_RE = /^\s*#\s*import\s+"([^"]+)"/
const ANGLE_IMPORT_RE = /^\s*#\s*import\s+<([^>]+)>/
const COMMENT_OR_BLANK_RE = /^\s*(?:\/\/|\*|\/\*|#\s*!|$)/

function headerStem(path: string): string {
  return (path.split('/').pop() || path).replace(/\.h$/i, '')
}

function isAndroidImport(line: string): string | null {
  const m = line.match(/^\s*import\s+(?:static\s+)?([\w.]+)(?:\.\*)?;?/)
  return m ? m[1] : null
}

const DEP_STOPWORDS = new Set([
  'android', 'core', 'common', 'lib', 'libs', 'sdk', 'java', 'google',
  'androidx', 'ktx', 'kotlin', 'annotation', 'annotations', 'ext',
  'support', 'compat', 'api',
])

/** Non-generic artifact tokens that could appear in source as imports/usages. */
function artifactTokens(artifact: string): string[] {
  const parts = artifact.split(/[^a-zA-Z0-9]+/).filter(Boolean)
  const tokens: string[] = [artifact]
  for (const part of parts) {
    if (part.length >= 4 && !DEP_STOPWORDS.has(part.toLowerCase())) tokens.push(part)
  }
  return tokens
}

/**
 * Build/runtime tooling dependencies are resolved by Gradle or the Kotlin
 * plugin and never appear in app source — flagging them is a guaranteed false
 * positive (com.android.tools.build:gradle, kotlin-stdlib, ...).
 */
function isBuildToolingDependency(group: string, artifact: string): boolean {
  const g = group.toLowerCase()
  const a = artifact.toLowerCase()
  if (g.startsWith('com.android.tools')) return true
  if (g.startsWith('org.jetbrains.kotlin')) return true
  if (a === 'kotlin-stdlib' || a === 'kotlin-reflect' || a === 'kotlin-test') return true
  return false
}

/**
 * Scan the project's ios/ and android/ trees for native configuration that
 * nothing references anymore: Podfile pods (or autolinked `node_modules` pods
 * whose package is gone), `settings.gradle` includes and gradle maven
 * dependencies with no source references, and unused `#import` / `import`
 * statements. Report-only — nothing is deleted.
 */
export function scanDeadNativeConfig(projectRoot: string): DeadNativeScanResult {
  const findings: DeadNativeConfig[] = []
  let scannedFiles = 0
  const deps = readInstalledDependencies(projectRoot)
  const iosRoot = join(projectRoot, 'ios')
  const androidRoot = join(projectRoot, 'android')

  // --- iOS: dead pods + unused imports ---
  const iosCandidates: { file: string; platform: NativePlatform }[] = []
  walkNativeDirs(iosRoot, 'ios', iosCandidates)
  const podfileFull = join(iosRoot, 'Podfile')
  const podfilePods = existsSync(podfileFull)
    ? parsePodfile(readFileSync(podfileFull, 'utf-8'))
    : []
  const podModules = new Set(podfilePods.map(p => p.name.split('/')[0]))

  for (const pod of podfilePods) {
    let reasoning: string | null = null
    if (pod.nodeModulesPath) {
      const pkg = packageFromNodeModulesPath(pod.nodeModulesPath)
      if (pkg && !isInstalled(deps, pkg)) {
        reasoning = `pod '${pod.name}' points at node_modules package '${pkg}', which is no longer in package.json — nothing references it anymore`
      }
    } else if (!isInstalled(deps, pod.name)) {
      const tokens = nativePackageTokens(pod.name)
      // Very short pod names (e.g. `App`) produce no tokens, so usage cannot be
      // verified — skip rather than accuse.
      if (tokens.length > 0 && !iosNativeFilesReference(projectRoot, tokens)) {
        reasoning = `pod '${pod.name}' is not in package.json and no iOS native source imports or uses it`
      }
    }
    if (reasoning) {
      findings.push({ platform: 'ios', file: 'ios/Podfile', line: pod.line, kind: 'pod', text: pod.raw, reasoning })
    }
  }

  for (const { file } of iosCandidates) {
    const base = file.split('/').pop() || file
    const ext = extname(base).toLowerCase()
    if (ext !== '.m' && ext !== '.mm') continue
    let content: string
    try {
      content = readFileSync(file, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading iOS source file')
      continue
    }
    scannedFiles++
    const lines = content.split('\n')
    lines.forEach((line, idx) => {
      const trimmed = line.trim()
      const angle = trimmed.match(ANGLE_IMPORT_RE)
      const local = trimmed.match(LOCAL_HEADER_IMPORT_RE)
      if (!angle && !local) return
      const importPath = (angle || local)![1]
      const stem = headerStem(importPath)
      if (!stem || stem.length < 2) return
      const body = lines
        .filter((l, i) => i !== idx && !COMMENT_OR_BLANK_RE.test(l))
        .join('\n')
      const tokens = new Set([stem])
      if (angle) {
        const module = importPath.split('/')[0]
        if (module && module !== stem) tokens.add(module)
      }
      const used = [...tokens].some(t => contentMentionsToken(body, t))
      if (used) return
      // Angle imports of system frameworks (UIKit, Foundation, ...) are
      // skipped — their module name rarely appears literally in code. Only
      // flag angle imports when the module is a pod declared in the Podfile.
      if (angle && !podModules.has(importPath.split('/')[0])) return
      const rel = relative(projectRoot, file)
      if (local) {
        const headerExists = iosCandidates.some(c => (c.file.split('/').pop() || '') === `${stem}.h`)
        if (!headerExists) {
          findings.push({ platform: 'ios', file: rel, line: idx + 1, kind: 'import', text: trimmed.slice(0, 140), reasoning: `'${stem}.h' does not exist anywhere in ios/ (dangling import)` })
        } else {
          findings.push({ platform: 'ios', file: rel, line: idx + 1, kind: 'import', text: trimmed.slice(0, 140), reasoning: `'${stem}' is never referenced in this file` })
        }
      } else {
        findings.push({ platform: 'ios', file: rel, line: idx + 1, kind: 'import', text: trimmed.slice(0, 140), reasoning: `imports pod module '${importPath.split('/')[0]}' but never uses it in this file` })
      }
    })
  }

  // --- Android: dead gradle includes/deps + unused imports ---
  const androidCandidates: { file: string; platform: NativePlatform }[] = []
  walkNativeDirs(androidRoot, 'android', androidCandidates)

  // settings.gradle / settings.gradle.kts includes
  for (const settingsFile of ['settings.gradle', 'settings.gradle.kts']) {
    const full = join(androidRoot, settingsFile)
    if (!existsSync(full)) continue
    const rel = relative(projectRoot, full)
    const content = readFileSync(full, 'utf-8')
    content.split('\n').forEach((line, idx) => {
      if (!/^\s*include\b/.test(line)) return
      const names = [...line.matchAll(/['"]:([^'"]+)['"]/g)].map(m => m[1])
      for (const name of names) {
        // Find projectDir override: project(':name').projectDir = new File(rootProject.projectDir, 'PATH')
        const dirMatch = content.match(new RegExp(`project\\(['"]:?${escapeRegExp(name)}['"]\\)\\.projectDir\\s*=\\s*[^,]*,\\s*['"]([^'"]+)['"]`))
        const relPath = dirMatch ? dirMatch[1] : null
        let reasoning: string | null = null
        if (relPath && relPath.includes('node_modules')) {
          const pkg = packageFromNodeModulesPath(relPath)
          if (pkg && !isInstalled(deps, pkg)) {
            reasoning = `include ':${name}' points at node_modules package '${pkg}', which is no longer in package.json — nothing references it anymore`
          }
        } else if (relPath && !existsSync(join(androidRoot, relPath))) {
          reasoning = `include ':${name}' points at '${relPath}', which does not exist on disk (dangling include)`
        } else if (relPath) {
          // Module exists — check no build.gradle references it and it isn't the
          // application module (recognized by its com.android.application plugin).
          const moduleDir = join(androidRoot, relPath)
          const moduleIsApp = [
            join(moduleDir, 'build.gradle'),
            join(moduleDir, 'build.gradle.kts'),
          ].some(f => {
            try {
              return existsSync(f) && readFileSync(f, 'utf-8').includes('com.android.application')
            } catch (err) {
              reportError(err, 'nativeScan: checking module for app plugin')
              return false
            }
          })
          if (!moduleIsApp) {
            const gradleFiles = androidCandidates.filter(c => /\.[gk]ts$/.test(c.file))
            const referenced = gradleFiles.some(c => {
              if (c.file.endsWith('settings.gradle') || c.file.endsWith('settings.gradle.kts')) return false
              try {
                return contentReferencesTokens(readFileSync(c.file, 'utf-8'), [`project(':${name}')`, `:${name}`])
              } catch (err) {
                reportError(err, 'nativeScan: checking gradle references')
                return false
              }
            })
            if (!referenced) {
              reasoning = `include ':${name}' exists at '${relPath}' but no build.gradle references it (unused local module)`
            }
          }
        }
        if (reasoning) {
          findings.push({ platform: 'android', file: rel, line: idx + 1, kind: 'gradle-include', text: line.trim().slice(0, 140), reasoning })
        }
      }
    })
  }

  // Build a corpus of android source (java/kt/xml) for maven-dep + group checks.
  const androidSourceFiles = androidCandidates.filter(c => /\.(java|kt|xml)$/.test(c.file))
  const corpus = androidSourceFiles.map(c => {
    try {
      return readFileSync(c.file, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading android source file')
      return ''
    }
  }).join('\n')

  // build.gradle maven dependencies never referenced in source
  for (const { file } of androidCandidates) {
    if (!/build\.gradle(?:\.kts)?$/.test(file)) continue
    let content: string
    try {
      content = readFileSync(file, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading build.gradle file')
      continue
    }
    const rel = relative(projectRoot, file)
    // Note: `classpath` deps (Android Gradle plugin etc.) are build-time
    // tooling, never referenced in app source — excluded to avoid false
    // positives on every project's root build.gradle.
    const depRe = /(?:implementation|api|compile|testImplementation|androidTestImplementation|debugImplementation|releaseImplementation|annotationProcessor|kapt|ksp)\s*\(?\s*['"]([^:'"]+):([^:'"]+):[^'"]*['"]/g
    let match: RegExpExecArray | null
    while ((match = depRe.exec(content)) !== null) {
      const group = match[1]
      const artifact = match[2]
      const line = content.slice(0, match.index).split('\n').length
      if (isBuildToolingDependency(group, artifact)) continue
      const groupUsed = group && corpus.toLowerCase().includes(group.toLowerCase())
      const tokens = artifactTokens(artifact)
      const artifactUsed = tokens.some(t => contentMentionsToken(corpus, t))
      if (!groupUsed && !artifactUsed) {
        findings.push({
          platform: 'android',
          file: rel,
          line,
          kind: 'gradle-dep',
          text: match[0].trim().slice(0, 140),
          reasoning: `maven dependency '${group}:${artifact}' never appears in android/ source (imports or usages)`,
        })
      }
    }
  }

  // Unused java/kotlin imports
  for (const { file } of androidSourceFiles) {
    if (!/\.(java|kt)$/.test(file)) continue
    let content: string
    try {
      content = readFileSync(file, 'utf-8')
    } catch (err) {
      reportError(err, 'nativeScan: reading android source file for imports')
      continue
    }
    scannedFiles++
    const rel = relative(projectRoot, file)
    const lines = content.split('\n')
    lines.forEach((line, idx) => {
      const imported = isAndroidImport(line)
      if (!imported) return
      if (imported.endsWith('.*')) return // wildcard imports are too risky to judge
      const simple = imported.split('.').pop() || ''
      if (!simple || simple.length < 2) return
      const body = lines
        .filter((l, i) => i !== idx && !COMMENT_OR_BLANK_RE.test(l))
        .join('\n')
      if (!contentMentionsToken(body, simple)) {
        findings.push({ platform: 'android', file: rel, line: idx + 1, kind: 'import', text: line.trim().slice(0, 140), reasoning: `'${simple}' is never referenced in this file` })
      }
    })
  }

  return { findings, scannedFiles }
}
