import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, relative, extname } from 'path'
import { reportPathChange } from './fileDiff'

export type NativePlatform = 'ios' | 'android'

export type NativeReferenceKind =
  | 'pod'       // Podfile `pod 'X'` declaration
  | 'pod-lock'  // Podfile.lock entry (regenerated by pod install)
  | 'gradle'    // settings.gradle include / build.gradle project() or maven dep
  | 'import'    // #import / import statement in native source
  | 'code'      // runtime usage (AppCenter.start(...), MainApplication wiring)
  | 'manifest'  // AndroidManifest.xml provider/activity
  | 'plist'     // Info.plist keys
  | 'pbxproj'   // Xcode project file (script phases, paths)

export interface NativeReference {
  platform: NativePlatform
  file: string // relative to project root
  line: number
  text: string
  kind: NativeReferenceKind
}

const SKIP_DIRS = new Set([
  'node_modules', 'build', '.gradle', '.cxx', 'Pods', 'DerivedData',
  'xcuserdata', '.git', '.expo', 'vendor', 'coverage', 'dist',
])

const RELEVANT_EXT = new Set([
  '.gradle', '.kts', '.pbxproj', '.plist', '.mm', '.m', '.h', '.swift',
  '.kt', '.java', '.xml', '.properties', '.podspec', '.xcconfig',
])

const RELEVANT_NAMES = new Set(['Podfile', 'Podfile.lock'])

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Name tokens that could reference a native package: the raw name (for
 * node_modules paths and gradle includes), the lowercased concatenation
 * (`appcenteranalytics`), and PascalCase (`AppCenter`, `AppCenterAnalytics`),
 * plus the scoped name for `@scope/name` path matches.
 */
export function nativePackageTokens(pkg: string): string[] {
  const base = pkg.split('/').pop() || pkg
  const stripped = base.replace(/^react-native-?/i, '') || base
  const parts = base.split(/[^a-zA-Z0-9]+/).filter(Boolean)
  const pascal = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  const strippedPascal = stripped.split(/[^a-zA-Z0-9]+/).filter(Boolean).map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
  const tokens = new Set<string>([
    pkg,                    // full scoped name, e.g. @sentry/react-native
    base,                   // appcenter-analytics
    base.replace(/-/g, ''), // appcenteranalytics
    parts.join('').toLowerCase(),
    pascal,                 // AppCenterAnalytics
    stripped,               // analytics (from react-native-analytics)
    strippedPascal,         // Analytics
  ])
  // A bare `react-native` / `ReactNative` token would false-positive on every
  // unrelated `node_modules/react-native-*` pod/gradle path when removing a
  // `react-native`-suffixed package (e.g. @sentry/react-native). The full scoped
  // name token already covers the real path match, so drop the ambiguous ones.
  tokens.delete('react-native')
  tokens.delete('ReactNative')
  tokens.delete('reactnative')
  // Short tokens (App from `app`) match AppDelegate/application classes
  // everywhere — require at least 4 characters to avoid false positives.
  return [...tokens].filter(t => t.length >= 4)
}

function isReferenceLine(line: string, tokens: string[]): boolean {
  for (const token of tokens) {
    const escaped = escapeRegExp(token)
    if (/^[A-Z]/.test(token)) {
      // PascalCase identifiers (AppCenter): start-boundary only, so
      // AppCenter matches AppCenter.start / AppCenterSecret / AppCenterAnalytics.
      const re = new RegExp(`(^|[^A-Za-z0-9])${escaped}`, 'i')
      if (re.test(line)) return true
    } else {
      // Lowercase tokens: full word boundary so `appcenter` matches
      // `com.microsoft.appcenter.utils` but not `appcenterfoo` / `okhttp3`
      // (a different Maven group than `okhttp`).
      const re = new RegExp(`(^|[^A-Za-z0-9])${escaped}([^A-Za-z0-9]|$)`, 'i')
      if (re.test(line)) return true
    }
  }
  return false
}

function classifyKind(file: string, line: string): NativeReferenceKind {
  const base = file.split('/').pop() || file
  const ext = extname(base).toLowerCase()
  if (base === 'Podfile') return 'pod'
  if (base === 'Podfile.lock') return 'pod-lock'
  if (ext === '.pbxproj') return 'pbxproj'
  if (ext === '.plist') return 'plist'
  if (base === 'AndroidManifest.xml') return 'manifest'
  if (ext === '.gradle' || ext === '.kts') return 'gradle'
  if (['.mm', '.m', '.h', '.swift', '.kt', '.java'].includes(ext)) {
    return /^\s*#?import\b/.test(line) ? 'import' : 'code'
  }
  return 'code'
}

function walkNativeDirs(
  root: string,
  platform: NativePlatform,
  out: { file: string; platform: NativePlatform }[]
): void {
  if (!existsSync(root)) return
  const stack = [root]
  while (stack.length > 0) {
    const dir = stack.pop() as string
    let entries: string[]
    try {
      entries = readdirSync(dir)
    } catch {
      continue
    }
    for (const entry of entries) {
      const full = join(dir, entry)
      let stat
      try {
        stat = statSync(full)
      } catch {
        continue
      }
      if (stat.isDirectory()) {
        if (!SKIP_DIRS.has(entry)) stack.push(full)
      } else if (RELEVANT_NAMES.has(entry) || RELEVANT_EXT.has(extname(entry).toLowerCase())) {
        out.push({ file: full, platform })
      }
    }
  }
}

/**
 * Scan the native ios/ and android/ trees for any line that references one of
 * the given packages (pod declarations, gradle includes/deps, native imports,
 * runtime usages, manifest/plist/pbxproj entries).
 */
export function scanNativeReferences(
  projectRoot: string,
  packageNames: string[]
): NativeReference[] {
  const refs: NativeReference[] = []
  const tokens = packageNames.flatMap(nativePackageTokens)
  const candidates: { file: string; platform: NativePlatform }[] = []
  walkNativeDirs(join(projectRoot, 'ios'), 'ios', candidates)
  walkNativeDirs(join(projectRoot, 'android'), 'android', candidates)

  for (const { file, platform } of candidates) {
    let content: string
    try {
      content = readFileSync(file, 'utf-8')
    } catch {
      continue
    }
    const rel = relative(projectRoot, file)
    content.split('\n').forEach((line, idx) => {
      const trimmed = line.trim()
      if (!trimmed || /^(?:\/\/|\*|\/\*|#\s*!)/.test(trimmed)) return
      if (isReferenceLine(line, tokens)) {
        refs.push({
          platform,
          file: rel,
          line: idx + 1,
          text: trimmed.slice(0, 140),
          kind: classifyKind(rel, line),
        })
      }
    })
  }
  return refs
}

function isStrippable(ref: NativeReference, tokens: string[]): boolean {
  switch (ref.kind) {
    case 'pod': {
      // `pod 'AppCenter'` or `pod 'AppCenter', :path => '../node_modules/appcenter/ios'`
      const podName = ref.text.match(/pod\s+['"]([^'"]+)['"]/)
      if (podName && isReferenceLine(podName[1], tokens)) return true
      return /node_modules\//.test(ref.text) && isReferenceLine(ref.text, tokens)
    }
    case 'pod-lock': {
      // `- AppCenter (5.0.3)` / `- AppCenter/...` / `- AppCenter (from `../node_modules/...`)`
      if (/^-\s/.test(ref.text)) return true
      return /node_modules\//.test(ref.text)
    }
    case 'gradle': {
      // `include ':appcenter'`, `project(':appcenter').projectDir = ...`,
      // `implementation project(':appcenter')`, `implementation 'com.x:appcenter:5.0.3'`
      if (/include\s+['"]:?/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      if (/project\(\s*['"]:?/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      if (/^\s*(implementation|api|compile|testImplementation|debugImplementation|releaseImplementation)\b/.test(ref.text) && isReferenceLine(ref.text, tokens)) return true
      return false
    }
    case 'import': {
      // `#import <AppCenter/AppCenter.h>` / `import com.microsoft.appcenter...`
      return /^\s*#?import\b/.test(ref.text) && isReferenceLine(ref.text, tokens)
    }
    default:
      // code usages, manifest providers, plist keys, pbxproj paths — reported,
      // never silently deleted (removing them can corrupt the build).
      return false
  }
}

export interface NativeStripResult {
  removed: NativeReference[]
  remaining: NativeReference[]
}

/**
 * Deterministically remove the safe, well-understood native references
 * (pod declarations, lockfile entries, gradle includes/project deps, native
 * import statements) from the project's ios/ and android/ trees. Everything
 * else — runtime usages, manifest/plist/pbxproj entries — is returned as
 * `remaining` for the caller to report (and optionally hand to the model).
 */
export function stripNativeReferences(
  projectRoot: string,
  packageNames: string[]
): NativeStripResult {
  const refs = scanNativeReferences(projectRoot, packageNames)
  const tokens = packageNames.flatMap(nativePackageTokens)
  const removed: NativeReference[] = []
  const remaining: NativeReference[] = []

  const toRemoveByFile = new Map<string, Set<number>>()
  for (const ref of refs) {
    if (isStrippable(ref, tokens)) {
      removed.push(ref)
      if (!toRemoveByFile.has(ref.file)) toRemoveByFile.set(ref.file, new Set())
      toRemoveByFile.get(ref.file)!.add(ref.line)
    } else {
      remaining.push(ref)
    }
  }

  for (const [rel, lineNums] of toRemoveByFile) {
    const full = join(projectRoot, rel)
    let original: string
    try {
      original = readFileSync(full, 'utf-8')
    } catch {
      continue
    }
    const kept = original
      .split('\n')
      .filter((_, idx) => !lineNums.has(idx + 1))
      .join('\n')
    if (kept !== original) {
      writeFileSync(full, kept, 'utf-8')
      reportPathChange(rel, original, kept)
    }
  }

  return { removed, remaining }
}
