/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with: node scripts/sync-reports.mjs
 *
 * The real documents vectalon writes to docs/vectalon/<cmd>/ in the demo
 * project (apps/website/demo/login-app). Every one of the 40 catalog
 * agents is represented, exactly as written. The completeness guard in
 * __tests__/reports.test.ts fails if this list ever drifts from the catalog.
 */

export interface ReportSample {
  /** CLI command that produced the report, e.g. `crash`. */
  cmd: string
  /** Display name (matches the agent catalog). */
  name: string
  /** The report's own verdict. */
  verdict: 'approved' | 'needs-attention' | 'changes-requested'
  /** Project the report was generated against. */
  project: string
  /** Where the report lives inside the project. */
  reportPath: string
  /** Exact command(s) that regenerate it. */
  regenerate: string
  /** The full document, exactly as written. */
  doc: string
}

export const REPORT_SAMPLES: ReportSample[] = [
  {
    cmd: "review",
    name: "PR Review Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/review/review.md",
    regenerate: "vectalon review",
    doc: "# PR Review — working-tree\n\n- Verdict: **changes-requested**\n- Files: 3 | Added lines: 11\n- Findings: 5 (0 error(s), 0 warning(s), 2 info)\n\n## apps/website/app/agents/page.tsx\n5 added line(s)\n- [info] magic-number (line 204) — Extract magic numbers into named constants.\n- [info] standard-tests (line 200) — Project standard (Unit tests: Jest + React Native Testing Library): jest / @testing-library/react-native present. — add or update tests for this change.\n- **LLM**: changes-requested — The `className` prop in the `div` element is not in kebab-case, which is a best practice in React Native.\n  - [warning] kebab-case-rule-id (line 12) — The `className` prop in the `div` element is not in kebab-case, which is a best practice in React Native. Suggestion: Change `className` to `className={styles.myClassName}`.\n\n## apps/website/app/page.tsx\n5 added line(s)\n- [info] magic-number (line 62) — Extract magic numbers into named constants.\n- [info] standard-tests (line 62) — Project standard (Unit tests: Jest + React Native Testing Library): jest / @testing-library/react-native present. — add or update tests for this change.\n- **LLM**: changes-requested — The code contains a typo in the `a` property of the first object in the array.\n  - [error] jsx-no-typography (line 12) — The text 'The optional model-driven agent does — but the 40 deterministic commands (review, security, SOC 2, GitHub PR triage, incident command, …) need no model at all. They run offline with a report and a verdict, zero model calls, free on every tier. Deterministic means reproducible, not static: every run re-scans your project’s current state, so the results are as fresh as your last command.' contains a typo in the `a` property. Suggestion: Correct the typo by replacing '—' with '—'\n\n## apps/website/lib/nav.ts\n1 added line(s)\n- [info] standard-tests (line 6) — Project standard (Unit tests: Jest + React Native Testing Library): jest / @testing-library/react-native present. — add or update tests for this change.\n- **LLM**: approved — The `href` prop in the navigation item is missing a key. (unsupported findings cleared by code verification)\n",
  },
  {
    cmd: "arch",
    name: "Architecture Review Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/arch/report.md",
    regenerate: "vectalon arch",
    doc: "# vectalon arch — Architecture Review\n\n- Verdict: **approved**\n- 6 source files in src/ (/Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app)\n- Findings: 0 (0 error(s), 0 warning(s), 0 info)\n\n## Modules\n\n| Module | Files | Fan-in | Fan-out | External packages |\n|--------|------:|-------:|--------:|-------------------|\n| __tests__ | 3 | 0 | 3 | @testing-library/react-native, react |\n| hooks | 1 | 2 | 1 | react |\n| screens | 1 | 1 | 1 | react, react-native |\n| services | 1 | 2 | 0 | — |\n\n## Findings\n\nNo architecture issues found — the module graph is clean.",
  },
  {
    cmd: "sec",
    name: "Security Review Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/sec/report.md",
    regenerate: "vectalon sec",
    doc: "# vectalon sec — Security Review\n\n- Verdict: **needs-attention**\n- 24 files scanned in /Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app\n- Findings: 19 (0 error(s), 8 warning(s), 11 info)\n\n## Dependency audit\n\n- 19 advisory(ies): 0 critical, 8 high, 11 moderate, 0 low\n\n| Package | Severity | Direct | Advisories |\n|---------|----------|--------|-----------|\n| @react-native/community-cli-plugin | high | no | 2 |\n| @testing-library/react-native | high | yes | 1 |\n| image-size | high | no | 2 |\n| metro | high | no | 3 |\n| metro-config | high | no | 1 |\n| metro-transform-worker | high | no | 1 |\n| postcss | high | no | 4 |\n| react-native | high | yes | 1 |\n| @expo/cli | moderate | no | 4 |\n| @expo/config | moderate | no | 1 |\n| @expo/config-plugins | moderate | no | 1 |\n| @expo/metro-config | moderate | no | 2 |\n| @expo/prebuild-config | moderate | no | 2 |\n| expo | moderate | yes | 6 |\n| expo-asset | moderate | no | 1 |\n| expo-constants | moderate | no | 1 |\n| jest-expo | moderate | yes | 1 |\n| uuid | moderate | no | 1 |\n| xcode | moderate | no | 1 |\n\n## Top recommendations\n\n1. @react-native/community-cli-plugin has 2 advisory(ies) at high severity (transitive) — Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range. (package.json:0)\n\n## Findings\n\n### [WARNING] dependency-vulnerability — package.json\n\n@react-native/community-cli-plugin has 2 advisory(ies) at high severity (transitive)\n\n- **Target:** `@react-native/community-cli-plugin` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\n@testing-library/react-native has 1 advisory(ies) at high severity\n\n- **Target:** `@testing-library/react-native` · deps\n- **Fix:** Run npm audit fix — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\nimage-size has 2 advisory(ies) at high severity (transitive)\n\n- **Target:** `image-size` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\nmetro has 3 advisory(ies) at high severity (transitive)\n\n- **Target:** `metro` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\nmetro-config has 1 advisory(ies) at high severity (transitive)\n\n- **Target:** `metro-config` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\nmetro-transform-worker has 1 advisory(ies) at high severity (transitive)\n\n- **Target:** `metro-transform-worker` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\npostcss has 4 advisory(ies) at high severity (transitive)\n\n- **Target:** `postcss` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [WARNING] dependency-vulnerability — package.json\n\nreact-native has 1 advisory(ies) at high severity\n\n- **Target:** `react-native` · deps\n- **Fix:** Run npm audit fix — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\n@expo/cli has 4 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `@expo/cli` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\n@expo/config has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `@expo/config` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\n@expo/config-plugins has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `@expo/config-plugins` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\n@expo/metro-config has 2 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `@expo/metro-config` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\n@expo/prebuild-config has 2 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `@expo/prebuild-config` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\nexpo has 6 advisory(ies) at moderate severity\n\n- **Target:** `expo` · deps\n- **Fix:** Run npm audit fix — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\nexpo-asset has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `expo-asset` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\nexpo-constants has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `expo-constants` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\njest-expo has 1 advisory(ies) at moderate severity\n\n- **Target:** `jest-expo` · deps\n- **Fix:** Run npm audit fix — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\nuuid has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `uuid` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n\n### [INFO] dependency-vulnerability — package.json\n\nxcode has 1 advisory(ies) at moderate severity (transitive)\n\n- **Target:** `xcode` · deps\n- **Fix:** Run npm audit fix and update the direct dependency that pulls it in — keep dependencies patched or pin to a fixed range.\n",
  },
  {
    cmd: "build-fix",
    name: "Build Fix Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/build-fix/report.md",
    regenerate: "vectalon build-fix --log metro.log",
    doc: "# vectalon build-fix — Build Fix Diagnosis\n\n- Build system: **metro** (auto-detected)\n- Verdict: **changes-requested**\n- Findings: 3 (1 error(s), 2 warning(s))\n\n## Fix plan\n\n1. Module resolution failure: The import path is wrong or the package is missing: check the specifier (extension, /index) in the failing file, `npm install` the package, add the directory to `watchFolders` in metro.config.js for monorepos, then `npx react-native start --reset-cache`.\n2. Asset resolution failure: The referenced image/font file does not exist at the given path (case matters): fix the require/import path, verify the file is committed, and for custom fonts check the fontFamily name matches the file registered in the app config.\n3. Syntax / transform error: The failing file does not parse under Metro's Babel pipeline: fix the syntax, or align the transform — check babel.config.js presets (babel-preset-expo / @react-native/babel-preset) and that the file extension matches its syntax (TS in .ts/.tsx, JSX in .jsx/.tsx).\n\n## Findings\n\n### [ERROR] module-resolution — log line 1\n\nRoot cause: Module resolution failure at log line 1.\n\n- **Class:** Module resolution failure · metro\n- **Fix:** The import path is wrong or the package is missing: check the specifier (extension, /index) in the failing file, `npm install` the package, add the directory to `watchFolders` in metro.config.js for monorepos, then `npx react-native start --reset-cache`.\n\n### [WARNING] asset-not-found — log line 10\n\nCorroborating failure: Asset resolution failure at log line 10.\n\n- **Class:** Asset resolution failure · metro\n- **Fix:** The referenced image/font file does not exist at the given path (case matters): fix the require/import path, verify the file is committed, and for custom fonts check the fontFamily name matches the file registered in the app config.\n\n### [WARNING] syntax-error — log line 12\n\nCorroborating failure: Syntax / transform error at log line 12.\n\n- **Class:** Syntax / transform error · metro\n- **Fix:** The failing file does not parse under Metro's Babel pipeline: fix the syntax, or align the transform — check babel.config.js presets (babel-preset-expo / @react-native/babel-preset) and that the file extension matches its syntax (TS in .ts/.tsx, JSX in .jsx/.tsx).\n\n## Log evidence (tail)\n\n```\nMetro has encountered an error: Unable to resolve module `./services/CreateLoginScreenEmailPasswordApi` from `src/hooks/useCreateLoginScreenEmailPassword.ts`.\n    None of these files exist:\n      * src/services/CreateLoginScreenEmailPasswordApi(.native|.ios.ts|.native.ts|.ts|.tsx)\n      * src/services/CreateLoginScreenEmailPasswordApi/index(.native|.ios.ts|.native.ts|.ts|.tsx)\n  1 | import { useState, useCallback } from 'react';\n  2 | import { createLoginScreenEmailPasswordApi } from '../services/CreateLoginScreenEmailPasswordApi';\n> 3 | import { createLoginScreenEmailPasswordApi } from '../services/CreateLoginScreenEmailPasswordApi';\n  4 |\nerror: bundling failed: Error: Unable to resolve module `../services/CreateLoginScreenEmailPasswordApi` from `src/hooks/useCreateLoginScreenEmailPassword.ts`\n  Metro has encountered an error: Invalid asset name: `./assets/logo.png`\n  (node:1234) [DEP0040] DeprecationWarning\nFailed to construct transformer: TransformError SyntaxError: /src/screens/CreateLoginScreenEmailPasswordScreen.tsx: Unexpected token\ninfo Metro waiting for the packager on port 8081, press Ctrl-C to exit\n```",
  },
  {
    cmd: "test-repair",
    name: "Test Repair Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/test-repair/report.md",
    regenerate: "vectalon test-repair --log jest.log",
    doc: "# vectalon test-repair — Test Fix Diagnosis\n\n- Test framework: **jest** (auto-detected)\n- Verdict: **changes-requested**\n- Findings: 2 (1 error(s), 1 warning(s))\n\n## Fix plan\n\n1. Assertion failure: The assertion failed — read the Expected vs Received diff at the failing line: the code under test returns something other than the test expects. Fix the implementation, the fixture, or the expectation (one of the three is wrong).\n2. Missing global in test environment: The test references a global Jest does not provide (fetch, localStorage, matchMedia…): define it in a setup file (jest.setup) or mock it per test with jest.fn().\n\n## Findings\n\n### [ERROR] assertion-failure — log line 4\n\nRoot cause: Assertion failure at log line 4.\n\n- **Class:** Assertion failure · jest\n- **Fix:** The assertion failed — read the Expected vs Received diff at the failing line: the code under test returns something other than the test expects. Fix the implementation, the fixture, or the expectation (one of the three is wrong).\n\n### [WARNING] missing-global — log line 13\n\nCorroborating failure: Missing global in test environment at log line 13.\n\n- **Class:** Missing global in test environment · jest\n- **Fix:** The test references a global Jest does not provide (fetch, localStorage, matchMedia…): define it in a setup file (jest.setup) or mock it per test with jest.fn().\n\n## Log evidence (tail)\n\n```\nFAIL src/hooks/__tests__/useCreateLoginScreenEmailPassword.test.ts\n  ● CreateLoginScreenEmailPassword hook › run() resolves data\n    expect(received).toBe(expected) // Object.is equality\n    Expected: \"login-created\"\n    Received: null\n      at Object.<anonymous> (src/hooks/__tests__/useCreateLoginScreenEmailPassword.test.ts:24:27)\n  ● CreateLoginScreenEmailPassword hook › run() surfaces errors\n    ReferenceError: fetch is not defined\n      at src/services/CreateLoginScreenEmailPasswordApi.ts:18:12\nTests: 1 failed, 1 passed, 2 total\nTest Suites: 1 failed, 1 total\n```",
  },
  {
    cmd: "refactor",
    name: "Refactoring Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/refactor/report.md",
    regenerate: "vectalon refactor",
    doc: "# vectalon refactor — Refactor Opportunities\n\n- Verdict: **needs-attention**\n- 11 source files scanned in /Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app\n- Findings: 3 (1 warning(s), 2 info)\n\n## Top opportunities\n\n1. Import React (from react) is never used — Remove the React specifier — dead imports confuse readers and trip noUnusedLocals in strict TS projects. (src/__tests__/CreateLoginScreenEmailPassword.tsx:4)\n2. console.log left in source — Remove it or route through a logger (console.warn/error for real problems) — stray logs leak state to production consoles. (gen-fixtures.js:39)\n3. String \"src/screens/LoginScreen.tsx\" is repeated 4 times — Hoist it to a named constant (or an i18n key) so the text and its changes live in one place. (gen-fixtures.js:15)\n\n## Findings\n\n### [WARNING] unused-import — src/__tests__/CreateLoginScreenEmailPassword.tsx:4\n\nImport React (from react) is never used\n\n- **Target:** `React` · dead-code\n- **Refactor:** Remove the React specifier — dead imports confuse readers and trip noUnusedLocals in strict TS projects.\n\n### [INFO] console-log — gen-fixtures.js:39\n\nconsole.log left in source\n\n- **Target:** `console.log` · logging\n- **Refactor:** Remove it or route through a logger (console.warn/error for real problems) — stray logs leak state to production consoles.\n\n### [INFO] duplicated-string — gen-fixtures.js:15\n\nString \"src/screens/LoginScreen.tsx\" is repeated 4 times\n\n- **Target:** `src/screens/LoginScreen.tsx` · duplication\n- **Refactor:** Hoist it to a named constant (or an i18n key) so the text and its changes live in one place.\n",
  },
  {
    cmd: "deps",
    name: "Dependency Upgrade Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/deps/report.md",
    regenerate: "vectalon deps",
    doc: "# vectalon deps — Dependency Upgrade Plan\n\n- Verdict: **needs-attention**\n- 18 direct dependencies in /Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app\n- Findings: 12 (0 error(s), 12 warning(s), 0 info)\n\n## Dependency audit\n\n- 19 advisory(ies): 0 critical, 8 high\n\n## Top upgrade paths\n\n1. @vectalon-dev/telemetry, @vectalon-dev/core, @vectalon-dev/rn, @vectalon-dev/website declare different versions of @types/node (^26.1.2 vs ^20.14.0). — Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n2. @vectalon-dev/telemetry, @vectalon-dev/core, @vectalon-dev/rn, @vectalon-dev/website declare different versions of typescript (^5.4.0 vs ^5.5.0). — Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n3. @vectalon-dev/website, @vectalon-dev/rn declare different versions of @vectalon-dev/core (workspace:* vs workspace:^). — Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n\n## Findings\n\n### [WARNING] duplicate--types-node — @types/node (^26.1.2 vs ^20.14.0)\n\n@vectalon-dev/telemetry, @vectalon-dev/core, @vectalon-dev/rn, @vectalon-dev/website declare different versions of @types/node (^26.1.2 vs ^20.14.0).\n\n- **Category:** duplicates\n- **Upgrade path:** Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n\n### [WARNING] duplicate-typescript — typescript (^5.4.0 vs ^5.5.0)\n\n@vectalon-dev/telemetry, @vectalon-dev/core, @vectalon-dev/rn, @vectalon-dev/website declare different versions of typescript (^5.4.0 vs ^5.5.0).\n\n- **Category:** duplicates\n- **Upgrade path:** Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n\n### [WARNING] duplicate--vectalon-dev-core — @vectalon-dev/core (workspace:* vs workspace:^)\n\n@vectalon-dev/website, @vectalon-dev/rn declare different versions of @vectalon-dev/core (workspace:* vs workspace:^).\n\n- **Category:** duplicates\n- **Upgrade path:** Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n\n### [WARNING] duplicate-ts-jest — ts-jest (^29.4.12 vs ^29.1.0)\n\n@vectalon-dev/website, @vectalon-dev/core, @vectalon-dev/rn declare different versions of ts-jest (^29.4.12 vs ^29.1.0).\n\n- **Category:** duplicates\n- **Upgrade path:** Align to one version at the workspace root (or one catalog) so native builds resolve a single copy — upgrade the older holders to the newest range.\n\n### [WARNING] vulnerability — @react-native/community-cli-plugin (declared range)\n\n@react-native/community-cli-plugin has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — @testing-library/react-native (declared range)\n\n@testing-library/react-native has a high advisory.\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — image-size (declared range)\n\nimage-size has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — metro (declared range)\n\nmetro has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — metro-config (declared range)\n\nmetro-config has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — metro-transform-worker (declared range)\n\nmetro-transform-worker has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — postcss (declared range)\n\npostcss has a high advisory (transitive).\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix and upgrade the direct dependency that pulls it in — then re-run this scan to confirm the tree is clean.\n\n### [WARNING] vulnerability — react-native (declared range)\n\nreact-native has a high advisory.\n\n- **Category:** vulnerability\n- **Upgrade path:** Run npm audit fix — then re-run this scan to confirm the tree is clean.\n",
  },
  {
    cmd: "a11y",
    name: "Accessibility Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/a11y/report.md",
    regenerate: "vectalon a11y",
    doc: "# vectalon a11y — Accessibility Review\n\n- Verdict: **approved**\n- 3 component files scanned in /Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app\n- Findings: 0 (0 error(s), 0 warning(s))\n\n## Findings\n\nNo accessibility issues found — the component tree is screen-reader friendly.",
  },
  {
    cmd: "release-ready",
    name: "Release Readiness Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/release-ready/report.md",
    regenerate: "vectalon release-ready",
    doc: "# vectalon release-ready — Release Readiness\n\n- Verdict: **changes-requested**\n- Version: 1.0.0 | Last tag: rn-v0.7.0-core-v0.1.0\n- Checks: 8 (1 error(s), 3 warning(s), 4 info)\n\n## Before you ship\n\n1. package.json version 1.0.0 is not newer than the last tag rn-v0.7.0-core-v0.1.0. Bump the version (semantic-release style: feat → minor, fix → patch) so the release publishes a new version.\n2. No CHANGELOG.md found. Keep a changelog — releases without release notes are invisible to users.\n3. 20 uncommitted change(s) — a release should ship from a clean tree. Commit (or stash) the outstanding changes so the release maps to a known revision.\n\n## Checklist\n\n- ✖ **Version**: package.json version 1.0.0 is not newer than the last tag rn-v0.7.0-core-v0.1.0. — Bump the version (semantic-release style: feat → minor, fix → patch) so the release publishes a new version.\n- ▲ **Changelog**: No CHANGELOG.md found. — Keep a changelog — releases without release notes are invisible to users.\n- ▲ **Working tree**: 20 uncommitted change(s) — a release should ship from a clean tree. — Commit (or stash) the outstanding changes so the release maps to a known revision.\n- ▲ **CI**: No .github/workflows directory — nothing runs tests or publishes on push. — Add CI (tests + typecheck) and a publish workflow before releasing.\n- ✓ **Lockfile**: Dependencies are locked.\n- ✓ **Tests**: A test script / jest config is configured.\n- ✓ **Secrets hygiene**: No .env file in the tree.\n- ✓ **Open markers**: 0 TODO/FIXME marker(s) across 11 source files.\n\n**Not ready — address the errors and warnings above.**",
  },
  {
    cmd: "bug-fix",
    name: "Autonomous Bug Fix Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/bug-fix/report.md",
    regenerate: "vectalon bug-fix",
    doc: "# vectalon bug-fix — Autonomous Bug Fix\n\nScanned `/Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app` — 1 findings, 1 auto-fixable, 0 applied, 0 refused (dirty tree).\n\n**Verdict: needs-attention**\n\n## Fix plan\n\n### [WARN] unused-import (auto)\n\n- **File**: `src/__tests__/CreateLoginScreenEmailPassword.tsx:4`\n- **Target**: `React`\n- **Message**: Import React (from react) is never used\n- **Fix**: Remove the React specifier — dead imports trip noUnusedLocals in strict TS projects.\n\n```diff\n-import React from 'react';\n+\n```\n",
  },
  {
    cmd: "crash",
    name: "Crash Intelligence Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/crash/report.md",
    regenerate: "vectalon crash --log crash.log",
    doc: "# vectalon crash — Crash Intelligence\n\nPlatform: **javascript**  ·  Verdict: **changes-requested**\nException: `Cannot read properties of null (reading 'email')`\nMessage: Cannot read properties of null (reading 'email')\n\n## Root cause: null-reference\n\nAccessing a property on a nullish value\n\n### Standard fix\n\nAdd optional chaining / default values at the nullish access, verify async data loads before render, and align the API response type with the consumer.\n\n## Investigation steps\n\n- Add optional chaining or default values\n- Verify async data is loaded before render\n- Check the API response shape matches the expected types\n- Investigate the top in-app frames from the report:\n-   - renderForm — src/screens/CreateLoginScreenEmailPasswordScreen.tsx:41\n-   - CreateLoginScreenEmailPasswordScreen — src/screens/CreateLoginScreenEmailPasswordScreen.tsx:19\n-   - useCreateLoginSession — src/hooks/useCreateLoginScreenEmailPassword.ts:12\n\n## Top frames\n\n- `renderForm — src/screens/CreateLoginScreenEmailPasswordScreen.tsx:41`\n- `CreateLoginScreenEmailPasswordScreen — src/screens/CreateLoginScreenEmailPasswordScreen.tsx:19`\n- `useCreateLoginSession — src/hooks/useCreateLoginScreenEmailPassword.ts:12`",
  },
  {
    cmd: "arch-score",
    name: "Mobile Architecture Scorecard",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/arch-score/report.md",
    regenerate: "vectalon arch-score",
    doc: "# vectalon arch-score — Mobile Architecture Scorecard\n\n**91/100 — grade A (approved)**\n\n| Dimension | Score | Weight | Detail |\n|---|---|---|---|\n| Circular dependencies | 100 | 30% | No cycles detected |\n| Layer boundaries | 80 | 20% | 1 shared→feature import(s) |\n| Module coupling | 100 | 15% | avg 1.8 imports per module (6 modules) |\n| Module cohesion | 100 | 15% | largest module has 3 file(s) across 4 module(s) |\n| Test coverage presence | 50 | 10% | 3 of 6 source files have a test sibling (50%) |\n| Nesting depth | 100 | 10% | deepest file sits 3 levels under src/ |\n\n## Top improvements\n\n- Move the 1 shared→feature import(s): features depend on shared, never the reverse.",
  },
  {
    cmd: "cicd",
    name: "CI/CD Intelligence Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/cicd/report.md",
    regenerate: "vectalon cicd",
    doc: "# vectalon cicd — CI/CD Intelligence\n\nSystems: none detected  ·  Files: 0  ·  Verdict: **approved**\n\nNo CI anti-patterns found.\n",
  },
  {
    cmd: "app-store",
    name: "App Store Readiness Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/app-store/report.md",
    regenerate: "vectalon app-store",
    doc: "# vectalon app-store — Store Readiness\n\nPlatforms: none  ·  Verdict: **approved**\n\n### [INFO] shared\n\nNo ios/ or android/ directories found\n\n**Fix**: Run this check in the native project root (or add the native folders) — store readiness only applies to native builds.\n",
  },
  {
    cmd: "soc2",
    name: "SOC2 Readiness Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/soc2/report.md",
    regenerate: "vectalon soc2",
    doc: "# vectalon soc2 — SOC2 Readiness\n\nScore: **27%** (1 pass, 4 partial, 6 fail)  ·  Verdict: **changes-requested**\n\n\n> This is a repository-evidence self-assessment, not an audit. A passing\n> score means the in-repo evidence exists; the audit itself needs process and\n> personnel evidence.\n\n### ⚠️ [Security] Authentication & authorization library in use — partial\n\n- **Evidence**: no auth/credential library declared\n- **Next step**: Adopt a credential/session library (expo-secure-store, react-native-keychain, jose) and document the auth flow.\n\n### ❌ [Security] Secrets excluded from version control — fail\n\n- **Evidence**: .env not found in .gitignore\n- **Next step**: Add .env (and .env.*) to .gitignore so secrets never enter the repository.\n\n### ✅ [Security] Dependencies locked for reproducible builds — pass\n\n- **Evidence**: package-lock.json committed\n- **Next step**: Commit a lockfile (package-lock.json / yarn.lock / pnpm-lock.yaml) for reproducible, auditable dependency sets.\n\n### ❌ [Availability] CI pipeline with tests — fail\n\n- **Evidence**: no CI workflows found\n- **Next step**: Add CI that runs tests on every push — SOC2 expects automated regression coverage.\n\n### ⚠️ [Processing Integrity] Automated tests in the repository — partial\n\n- **Evidence**: no test files detected\n- **Next step**: Add unit/integration tests for core flows — processing integrity needs verifiable behavior.\n\n### ⚠️ [Confidentiality] Encrypted communication (TLS) — partial\n\n- **Evidence**: no explicit TLS configuration found\n- **Next step**: Ensure every API endpoint uses HTTPS and ATS is not disabled.\n\n### ❌ [Privacy] Privacy policy documented — fail\n\n- **Evidence**: no privacy policy document found\n- **Next step**: Document data collection, retention, and deletion — required for the Privacy criterion.\n\n### ⚠️ [Security] Structured logging for audit trails — partial\n\n- **Evidence**: no structured logging library declared\n- **Next step**: Adopt a structured logger and log auth events, admin actions, and errors with timestamps.\n\n### ❌ [Availability] Data backup strategy in place — fail\n\n- **Evidence**: no backup strategy found in the repo\n- **Next step**: Document and automate database/state backups with recovery-time objectives (RTO/RPO).\n\n### ❌ [Security] Incident response runbook — fail\n\n- **Evidence**: no incident response runbook found\n- **Next step**: Write an INCIDENT.md runbook: severity levels, on-call, containment steps, postmortem template.\n\n### ❌ [Security] Dependency vulnerability scanning — fail\n\n- **Evidence**: npm audit / dependabot / renovate configured\n- **Next step**: Run `npm audit` in CI (or enable Dependabot) so vulnerable dependencies are caught continuously.\n",
  },
  {
    cmd: "tokens",
    name: "Design Token Sync Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/tokens/report.md",
    regenerate: "vectalon tokens",
    doc: "# vectalon tokens — Design Token Sync\n\nToken file: `none`  ·  Tokens: 0  ·  Verdict: **approved**\n\n### [INFO] orphan-token\n\nNo design-token file found (tokens.json / design-tokens.json / theme.json).\n\n**Fix**: Create a style-dictionary-style token file so this agent can check drift.\n",
  },
  {
    cmd: "team-stats",
    name: "Team Productivity Analytics",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/team-stats/report.md",
    regenerate: "vectalon team-stats",
    doc: "# vectalon team-stats — Team Productivity Analytics\n\nCommits: 308  ·  Authors: 3  ·  Bus factor: 1  ·  Cadence: 18.1/day  ·  Verdict: **needs-attention**\n\n\n## Authors\n\n| Author | Commits | Share |\n|---|---|---|\n| Bhishak Sanyal | 289 | 94% |\n| vectalon-benchmark[bot] | 12 | 4% |\n| dependabot[bot] | 7 | 2% |\n\n## Categories\n\n- added: 142\n- changed: 99\n- fixed: 35\n- removed: 2\n- security: 8\n- performance: 0\n- deprecated: 0\n- other: 22\n\n## Findings\n\n### [WARN] bus-factor\n\nBus factor 1: Bhishak Sanyal owns 94% of commits\n\n**Suggestion**: Pair on critical modules and rotate ownership so a single departure cannot stall the project.\n",
  },
  {
    cmd: "perms",
    name: "Agent Permissions Audit",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/perms/report.md",
    regenerate: "vectalon perms",
    doc: "# vectalon perms — Agent Permissions Audit\n\nConfig files: 0  ·  Verdict: **approved**\n\n\nNo agent/MCP config files found — nothing to audit.\n",
  },
  {
    cmd: "dashboard",
    name: "Engineering Dashboard",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/dashboard/report.md",
    regenerate: "vectalon dashboard",
    doc: "# Engineering Dashboard\n\nOverall: **changes-requested**  ·  38 agents, 96 findings (3 errors, 54 warnings)\n\n\n| Agent | Verdict | Errors | Warnings | Info |\n|---|---|---|---|---|\n| a11y | approved | 0 | 0 | 0 |\n| app-store | approved | 0 | 0 | 1 |\n| arch | approved | 0 | 0 | 0 |\n| arch-score | approved | 0 | 0 | 0 |\n| audit | approved | 0 | 0 | 1 |\n| bug-fix | needs-attention | 0 | 1 | 0 |\n| build-fix | approved | 0 | 0 | 0 |\n| cicd | approved | 0 | 0 | 0 |\n| cost | approved | 0 | 0 | 1 |\n| dataset | approved | 0 | 0 | 1 |\n| deps | needs-attention | 0 | 12 | 0 |\n| dx | changes-requested | 0 | 0 | 0 |\n| evals | changes-requested | 0 | 1 | 0 |\n| figma | approved | 0 | 0 | 1 |\n| gh-ci | approved | 0 | 0 | 0 |\n| gh-issue | approved | 0 | 0 | 0 |\n| gh-pr | changes-requested | 0 | 17 | 6 |\n| gh-sec | changes-requested | 0 | 1 | 0 |\n| governance | needs-attention | 0 | 2 | 6 |\n| incident | changes-requested | 0 | 0 | 0 |\n| lora | changes-requested | 1 | 0 | 0 |\n| monitor | needs-attention | 0 | 0 | 0 |\n| observability | needs-attention | 0 | 5 | 0 |\n| perms | approved | 0 | 0 | 0 |\n| play-store | changes-requested | 1 | 0 | 0 |\n| refactor | needs-attention | 0 | 1 | 2 |\n| release-predict | needs-attention | 0 | 0 | 2 |\n| release-ready | changes-requested | 1 | 3 | 4 |\n| repos | approved | 0 | 0 | 1 |\n| review | changes-requested | 0 | 0 | 0 |\n| search | approved | 0 | 0 | 0 |\n| sec | needs-attention | 0 | 8 | 11 |\n| sentry | approved | 0 | 0 | 0 |\n| soc2 | changes-requested | 0 | 0 | 0 |\n| team-stats | needs-attention | 0 | 1 | 0 |\n| test-repair | approved | 0 | 0 | 0 |\n| tokens | approved | 0 | 0 | 1 |\n| train | changes-requested | 0 | 2 | 0 |\n\nNeeds action: lora, play-store, release-ready\n",
  },
  {
    cmd: "figma",
    name: "Figma-to-code Sync Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/figma/report.md",
    regenerate: "vectalon figma",
    doc: "# vectalon figma — Figma-to-code Sync\n\nDesign file: `none`  ·  Colors: 0  ·  Components: 0  ·  Verdict: **approved**\n\n### [INFO] missing-token — \n\nNo Figma design export found (figma.json / design-export.json / design.json).\n\n**Fix**: Export the design file as JSON and drop it at the repo root so this agent can check design↔code drift.\n",
  },
  {
    cmd: "sentry",
    name: "Sentry Intelligence Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/sentry/report.md",
    regenerate: "vectalon telemetry --path telemetry/ && vectalon sentry",
    doc: "# vectalon sentry — Sentry Intelligence\n\nTelemetry files: 2  ·  Events: 47  ·  Crash classes: 7  ·  Verdict: **approved**\n\n### [CRITICAL] Error\n\nEvents: 41  ·  Users: 0  ·  Releases: 1.0.0\n\n\nBucket: unknown\n\nProbable cause: Error: Attempted to use an object of type View as an RCTView\n\nInvestigation:\n- Check what changed in release 1.0.0 — the crash is attributed to it\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n- Investigate the top in-app frames from the report:\n-   - (anonymous) — src/screens/LoginScreen.tsx:88\n\n### [INFO] sentry-1786785284868-l7w11o\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n\n### [INFO] sentry-1786785284868-ptu0dm\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n\n### [INFO] sentry-1786785284868-um1wp2\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n\n### [INFO] sentry-1786785284868-0zcryl\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n\n### [INFO] sentry-1786785284868-qwke20\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n\n### [INFO] sentry-1786785284868-9o6qyb\n\nEvents: 1  ·  Users: 0  ·  Releases: unknown\n\n\nBucket: unknown\n\nProbable cause: Could not automatically classify this issue\n\nInvestigation:\n- Reproduce the issue locally\n- Capture logs and stack traces\n- Trace recent changes that could relate\n",
  },
  {
    cmd: "observability",
    name: "Mobile Observability Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/observability/report.md",
    regenerate: "vectalon telemetry --path telemetry/ && vectalon observability",
    doc: "# vectalon observability — Mobile Observability\n\nTraces scanned: 0  ·  Slow traces: 0  ·  Verdict: **needs-attention**\n\n### [WARN] no-sentry-init\n\nSentry init not detected in any source file\n\n**Fix**: Wire up sentry init so crashes and performance data actually reach your observability backend.\n\n### [WARN] no-crash-handler\n\nCrash handler not detected in any source file\n\n**Fix**: Wire up crash handler so crashes and performance data actually reach your observability backend.\n\n### [WARN] no-analytics-sdk\n\nAnalytics SDK not detected in any source file\n\n**Fix**: Wire up analytics sdk so crashes and performance data actually reach your observability backend.\n\n### [WARN] no-network-breadcrumb\n\nNetwork breadcrumbs not detected in any source file\n\n**Fix**: Wire up network breadcrumbs so crashes and performance data actually reach your observability backend.\n\n### [WARN] no-performance-tracing\n\nPerformance tracing not detected in any source file\n\n**Fix**: Wire up performance tracing so crashes and performance data actually reach your observability backend.\n",
  },
  {
    cmd: "governance",
    name: "Enterprise Governance Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/governance/report.md",
    regenerate: "vectalon governance",
    doc: "# vectalon governance — Enterprise Governance\n\nChecks: 9  ·  Verdict: **needs-attention**\n\n| Check | Status | Evidence |\n|---|---|---|\n| License file | ❌ fail | no LICENSE file at repo root |\n| Security policy | ❌ fail | no SECURITY.md (or .github/SECURITY.md) |\n| Contributing guide | ⚠️ warn | no CONTRIBUTING.md |\n| CODEOWNERS | ⚠️ warn | no CODEOWNERS (or .github/CODEOWNERS) |\n| PR template | ⚠️ warn | no PR template |\n| Lockfile | ✅ pass | package-lock.json |\n| SBOM | ⚠️ warn | no SBOM (sbom.json / cyclonedx) |\n| Dependabot | ⚠️ warn | no .github/dependabot.yml |\n| CI workflows | ⚠️ warn | no .github/ directory |\n\n## Findings\n\n### [WARN] missing-license\n\nLicense file is missing: Add a LICENSE so downstream consumers know their rights.\n\n**Fix**: Add a LICENSE so downstream consumers know their rights.\n\n### [WARN] missing-security-policy\n\nSecurity policy is missing: Document how to privately report a vulnerability.\n\n**Fix**: Document how to privately report a vulnerability.\n\n### [INFO] missing-contributing\n\nContributing guide not found: Add a contributing guide so external contributors know the workflow.\n\n**Fix**: Add a contributing guide so external contributors know the workflow.\n\n### [INFO] missing-codeowners\n\nCODEOWNERS not found: Add CODEOWNERS so the right people review sensitive paths.\n\n**Fix**: Add CODEOWNERS so the right people review sensitive paths.\n\n### [INFO] missing-pr-template\n\nPR template not found: Add a PR template with checklist + test instructions.\n\n**Fix**: Add a PR template with checklist + test instructions.\n\n### [INFO] missing-sbom\n\nSBOM not found: Generate an SBOM (e.g. `syft dir:. -o cyclonedx-json`) for supply-chain visibility.\n\n**Fix**: Generate an SBOM (e.g. `syft dir:. -o cyclonedx-json`) for supply-chain visibility.\n\n### [INFO] missing-dependabot\n\nDependabot not found: Add Dependabot config so dependency advisories land as PRs.\n\n**Fix**: Add Dependabot config so dependency advisories land as PRs.\n\n### [INFO] missing-ci\n\nCI workflows not found: Add CI so every PR is tested before merge.\n\n**Fix**: Add CI so every PR is tested before merge.\n",
  },
  {
    cmd: "audit",
    name: "Org-wide Audit Trail Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/audit/report.md",
    regenerate: "vectalon audit",
    doc: "# vectalon audit — Org-wide Audit Trail\n\nEntries: 0  ·  Files: 0  ·  Verdict: **approved**\n\n\n## Findings\n\n### [INFO] no-trail\n\nNo audit trail found (.vectalon/audit or audit).\n\n**Fix**: Have agents append JSONL audit entries (seq, timestamp, actor, action) so the org has an immutable trail.\n",
  },
  {
    cmd: "repos",
    name: "Multi-repository Memory Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/repos/report.md",
    regenerate: "vectalon repos",
    doc: "# vectalon repos — Multi-repository Memory\n\nManifest: none  ·  Repos: 0  ·  Verdict: **approved**\n\n\n## Findings\n\n### [INFO] no-manifest\n\nNo workspace manifest at .vectalon/repos.json.\n\n**Fix**: Create .vectalon/repos.json with {\"repos\":[{\"name\",\"path\"}]} listing sibling checkouts.\n",
  },
  {
    cmd: "release-predict",
    name: "Release Prediction Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/release-predict/report.md",
    regenerate: "vectalon release-predict",
    doc: "# vectalon release-predict — Release Prediction\n\nRisk: **high**  ·  Score: 44/100  ·  Window: 14d (263 commits)  ·  Verdict: **needs-attention**\n\nHigh risk — require a code freeze, full regression pass, and a slow staged rollout with rollback ready.\n\n## Factors\n\n| Factor | Value | Weight | Direction |\n|---|---|---|---|\n| release-window-commits | 263 | 20% | lower = safer |\n| fix-density | 0.194 | 35% | lower = safer |\n| refactor-density | 0.091 | 15% | lower = safer |\n| hours-since-last-commit | 9.2 | 10% | lower = safer |\n| breaking-changes | 0 | 10% | lower = safer |\n| authors-in-window | 2 | 10% | higher = safer |\n\n## Findings\n\n### [INFO] release-risk\n\nPredicted release risk high (score 44/100) for the 14-day window: High risk — require a code freeze, full regression pass, and a slow staged rollout with rollback ready.\n\n**Suggestion**: Add release-gate checks: code freeze, full suite on the release candidate, smoke test on staging, staged rollout.\n\n### [INFO] fix-density\n\n51 of 263 window commit(s) are fixes/rollbacks (19%)\n\n**Suggestion**: Investigate the root causes instead of stacking fixes — recurring fix commits predict an unstable release.\n",
  },
  {
    cmd: "play-store",
    name: "Deep Play Store Readiness Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/play-store/report.md",
    regenerate: "vectalon play-store",
    doc: "# vectalon play-store — Deep Play Store Readiness\n\nChecks: 1  ·  Verdict: **changes-requested**\n\n| Check | Status | Detail |\n|---|---|---|\n| AndroidManifest.xml | ❌ fail | No AndroidManifest.xml found under android/ |\n\n## Findings\n\n### [ERROR] manifest\n\nNo AndroidManifest.xml found under android/\n\n**Fix**: Create the manifest in android/app/src/main/ — Play submission requires it.\n",
  },
  {
    cmd: "dataset",
    name: "Fine-tuning Dataset Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/dataset/report.md",
    regenerate: "vectalon dataset",
    doc: "# vectalon dataset — Fine-tuning Dataset\n\nFiles: 0  ·  Examples: 0  ·  Verdict: **approved**\n\n### [INFO] no-dataset\n\nNo dataset directory found (.vectalon/dataset, dataset, or training-data).\n\n**Fix**: Export training examples as JSONL into one of those directories so this agent can validate the dataset.\n",
  },
  {
    cmd: "lora",
    name: "LoRA Training Readiness Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/lora/report.md",
    regenerate: "vectalon lora",
    doc: "# vectalon lora — LoRA Training Readiness\n\nChecks: 1  ·  Verdict: **changes-requested**\n\n| Check | Status | Detail |\n|---|---|---|\n| Training config | ❌ fail | No .vectalon/lora/config.json (or YAML) found |\n\n## Findings\n\n### [ERROR] config\n\nNo .vectalon/lora/config.json (or YAML) found\n\n**Fix**: Create the config with dataset path, base model, r/alpha, and output dir.\n",
  },
  {
    cmd: "gh-pr",
    name: "GitHub PR Triage Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/gh-pr/report.md",
    regenerate: "vectalon gh-pr",
    doc: "# vectalon gh-pr — GitHub PR Triage\n\nSource: gh-cli  ·  PRs: 13  ·  Verdict: **changes-requested**\n\n| # | PR | Author | Age | Size | Review | CI | Mergeable | Verdict |\n|---|---|---|---|---|---|---|---|---|\n| 12 | chore(deps-dev): bump typescript from 5.9.3 to 7.0.2 | app/dependabot | 15d | 59136 |  | failing (test, comment, coverage, bench) | CONFLICTING | changes-requested |\n| 7 | chore(deps-dev): bump eslint from 8.57.1 to 10.8.0 | app/dependabot | 15d | 59270 |  | failing (test, comment, coverage, bench) | CONFLICTING | changes-requested |\n| 20 | chore(deps): bump actions/upload-artifact from 4 to 7 | app/dependabot | 9d | 41211 |  | passing | CONFLICTING | changes-requested |\n| 19 | chore(deps): bump @babel/parser from 7.29.8 to 8.0.4 | app/dependabot | 9d | 81239 |  | failing (test, Analyze (javascript), comment, coverage, bench) | CONFLICTING | changes-requested |\n| 18 | chore(deps): bump codecov/codecov-action from 5 to 7 | app/dependabot | 9d | 81209 |  | failing (test, comment, coverage, bench) | CONFLICTING | changes-requested |\n| 28 | chore(deps-dev): bump @typescript-eslint/eslint-plugin from 7.18.0 to 8.67.0 | app/dependabot | 1d | 171 |  | failing (test, validate) | MERGEABLE | changes-requested |\n| 26 | chore(deps-dev): bump tailwindcss from 3.4.19 to 4.3.3 | app/dependabot | 1d | 270 |  | failing (test, validate, comment, bench) | MERGEABLE | changes-requested |\n| 24 | chore(deps): bump react-dom and @types/react-dom | app/dependabot | 1d | 51 |  | failing (test, validate, comment, bench) | MERGEABLE | changes-requested |\n| 21 | chore(deps): bump github/codeql-action from 4.37.3 to 4.37.6 | app/dependabot | 9d | 6 |  | passing | MERGEABLE | approved |\n| 30 | chore(deps-dev): bump @typescript-eslint/parser from 7.18.0 to 8.67.0 | app/dependabot | 1d | 130 |  | passing | MERGEABLE | approved |\n| 29 | chore(deps): bump ws from 8.21.2 to 8.21.3 | app/dependabot | 1d | 12 |  | passing | MERGEABLE | approved |\n| 27 | chore(deps-dev): bump @types/node from 20.19.43 to 26.2.0 | app/dependabot | 1d | 193 |  | passing | MERGEABLE | approved |\n| 25 | chore(deps-dev): bump turbo from 2.10.8 to 2.10.9 | app/dependabot | 1d | 60 |  | passing | MERGEABLE | approved |\n\n## Findings\n\n### [WARN] pr-ci-failing (PR #28)\n\nPR #28 CI is failing (test, validate).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-ci-failing (PR #26)\n\nPR #26 CI is failing (test, validate, comment, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-ci-failing (PR #24)\n\nPR #24 CI is failing (test, validate, comment, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-huge (PR #20)\n\nPR #20 touches 41211 lines (38601+/2610-) — a review will miss defects at this size.\n\n**Suggestion**: Split into reviewable chunks of a few hundred lines each.\n\n### [WARN] pr-conflict (PR #20)\n\nPR #20 has merge conflicts with its base branch.\n\n**Suggestion**: Re-base on the latest base branch and resolve conflicts.\n\n### [INFO] pr-idle (PR #20)\n\nPR #20 has had no activity in 8 days.\n\n**Suggestion**: Nudge the author or reassign to keep the change moving.\n\n### [WARN] pr-huge (PR #19)\n\nPR #19 touches 81239 lines (63497+/17742-) — a review will miss defects at this size.\n\n**Suggestion**: Split into reviewable chunks of a few hundred lines each.\n\n### [WARN] pr-ci-failing (PR #19)\n\nPR #19 CI is failing (test, Analyze (javascript), comment, coverage, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-conflict (PR #19)\n\nPR #19 has merge conflicts with its base branch.\n\n**Suggestion**: Re-base on the latest base branch and resolve conflicts.\n\n### [INFO] pr-idle (PR #19)\n\nPR #19 has had no activity in 8 days.\n\n**Suggestion**: Nudge the author or reassign to keep the change moving.\n\n### [WARN] pr-huge (PR #18)\n\nPR #18 touches 81209 lines (63467+/17742-) — a review will miss defects at this size.\n\n**Suggestion**: Split into reviewable chunks of a few hundred lines each.\n\n### [WARN] pr-ci-failing (PR #18)\n\nPR #18 CI is failing (test, comment, coverage, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-conflict (PR #18)\n\nPR #18 has merge conflicts with its base branch.\n\n**Suggestion**: Re-base on the latest base branch and resolve conflicts.\n\n### [INFO] pr-idle (PR #18)\n\nPR #18 has had no activity in 8 days.\n\n**Suggestion**: Nudge the author or reassign to keep the change moving.\n\n### [INFO] pr-stale (PR #12)\n\nPR #12 has been open 15 days.\n\n**Suggestion**: Confirm it still targets the current trunk before it goes stale.\n\n### [WARN] pr-huge (PR #12)\n\nPR #12 touches 59136 lines (55452+/3684-) — a review will miss defects at this size.\n\n**Suggestion**: Split into reviewable chunks of a few hundred lines each.\n\n### [WARN] pr-ci-failing (PR #12)\n\nPR #12 CI is failing (test, comment, coverage, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-conflict (PR #12)\n\nPR #12 has merge conflicts with its base branch.\n\n**Suggestion**: Re-base on the latest base branch and resolve conflicts.\n\n### [INFO] pr-idle (PR #12)\n\nPR #12 has had no activity in 8 days.\n\n**Suggestion**: Nudge the author or reassign to keep the change moving.\n\n### [INFO] pr-stale (PR #7)\n\nPR #7 has been open 15 days.\n\n**Suggestion**: Confirm it still targets the current trunk before it goes stale.\n\n### [WARN] pr-huge (PR #7)\n\nPR #7 touches 59270 lines (55323+/3947-) — a review will miss defects at this size.\n\n**Suggestion**: Split into reviewable chunks of a few hundred lines each.\n\n### [WARN] pr-ci-failing (PR #7)\n\nPR #7 CI is failing (test, comment, coverage, bench).\n\n**Suggestion**: Fix the failing checks or the merge is blocked by the CI gate.\n\n### [WARN] pr-conflict (PR #7)\n\nPR #7 has merge conflicts with its base branch.\n\n**Suggestion**: Re-base on the latest base branch and resolve conflicts.\n",
  },
  {
    cmd: "gh-issue",
    name: "GitHub Issue Intelligence Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/gh-issue/report.md",
    regenerate: "vectalon gh-issue",
    doc: "# vectalon gh-issue — GitHub Issue Triage\n\nSource: gh-cli  ·  Open: 0  ·  Stale: 0  ·  Unassigned: 0  ·  Verdict: **approved**\n\n| # | Title | Author | Age | Labels | Assignees | Verdict |\n|---|---|---|---|---|---|---|\n\n## Findings\n",
  },
  {
    cmd: "gh-ci",
    name: "GitHub Workflow Reliability Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/gh-ci/report.md",
    regenerate: "vectalon gh-ci",
    doc: "# vectalon gh-ci — GitHub Workflow Reliability\n\nSource: gh-cli  ·  Workflows: 8  ·  Runs: 0  ·  Flaky: 0  ·  Verdict: **approved**\n\n| Workflow | Runs | Pass | Fail | Fail rate | Flaky | Avg |\n|---|---|---|---|---|---|---|\n| CI | 0 | 0 | 0 | 0% | no | 4m |\n| CodeQL | 0 | 0 | 0 | 0% | no | 2m |\n| Publish Packages | 0 | 0 | 0 | 0% | no | 2m |\n| Nightly Smoke | 0 | 0 | 0 | 0% | no | 2m |\n| Benchmark leaderboard (nightly) | 0 | 0 | 0 | 0% | no | 26m |\n| PR leaderboard comment | 0 | 0 | 0 | 0% | no | 4m |\n| PR Validation | 0 | 0 | 0 | 0% | no | 4m |\n| Dependabot Updates | 0 | 0 | 0 | 0% | no | 2m |\n\n## Findings\n",
  },
  {
    cmd: "gh-sec",
    name: "GitHub Security Posture Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/gh-sec/report.md",
    regenerate: "vectalon gh-sec",
    doc: "# vectalon gh-sec — GitHub Security Posture\n\nSource: none  ·  Dependabot: 0 open (0 critical/high)  ·  Secrets: 0  ·  Protection: off  ·  Verdict: **changes-requested**\n\n## Findings\n\n### [WARN] no-data ((all))\n\nNo GitHub security data available — gh is missing, unauthenticated, or this is not a GitHub repo.\n\n**Suggestion**: Install and auth the GitHub CLI, or pass --file with a gh-sec export (dependabot, secretScanning, branchProtection).\n",
  },
  {
    cmd: "monitor",
    name: "Observability Dashboard Agent",
    verdict: "needs-attention",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/monitor/report.md",
    regenerate: "vectalon telemetry --path telemetry/ && vectalon monitor",
    doc: "# vectalon monitor — Observability Dashboard\n\nCrash classes: 7  ·  Telemetry events: 0  ·  Verdict: **needs-attention**\n\n| Surface | Verdict | Summary |\n|---|---|---|\n| Crash classes (Sentry) | approved | 7 crash class(es) ranked |\n| Observability audit | needs-attention | 5 instrumentation/trace finding(s) |\n| Crash intelligence | no-data | No crash report yet |\n| Engineering dashboard | no-data | No dashboard report yet |\n\n## Findings\n",
  },
  {
    cmd: "evals",
    name: "Model Evaluation Harness",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/evals/report.md",
    regenerate: "vectalon evals",
    doc: "# vectalon evals — Model Evaluation\n\nCases: 0  ·  Pass: 0/0 (0%)  ·  Verdict: **changes-requested**\n\n| Case | Mode | Result | Note |\n|---|---|---|---|\n\n## Findings\n\n### [WARN] no-cases\n\nNo eval cases found at /Users/bhishaksanyal/Documents/Github/Vectalon/apps/website/demo/login-app/.vectalon/evals/cases.json (or the file is invalid).\n\n**Suggestion**: Create .vectalon/evals/cases.json with { cases: [{ id, input, expected, actual, mode }] }.\n",
  },
  {
    cmd: "search",
    name: "Semantic Code Search Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/search/report.md",
    regenerate: "vectalon search",
    doc: "# vectalon search — \"login\"\n\nFiles scanned: 8  ·  Hits: 18  ·  1ms\n\n## src/__tests__/CreateLoginScreenEmailPassword.tsx\n\n- `1` // TDD test suite for CreateLoginScreenEmailPassword — written before implementation.\n- `2` // Run `npm test CreateLoginScreenEmailPassword` to verify the implementation satisfies these requirements.\n- `6` import { CreateLoginScreenEmailPasswordScreen } from '../screens/CreateLoginScreenEmailPasswordScreen';\n## src/__tests__/useCreateLoginScreenEmailPassword.ts\n\n- `1` // TDD test suite for useCreateLoginScreenEmailPassword — written before implementation.\n- `4` import { useCreateLoginScreenEmailPassword } from '../hooks/useCreateLoginScreenEmailPassword';\n- `6` describe('useCreateLoginScreenEmailPassword', () => {\n## src/hooks/useCreateLoginScreenEmailPassword.ts\n\n- `2` import { createLoginScreenEmailPasswordApi } from '../services/CreateLoginScreenEmailPasswordApi';\n- `4` interface UseCreateLoginScreenEmailPasswordState {\n- `10` export function useCreateLoginScreenEmailPassword(): UseCreateLoginScreenEmailPasswordState & { run: () => Promise<void> } {\n## src/screens/CreateLoginScreenEmailPasswordScreen.tsx\n\n- `3` import { useCreateLoginScreenEmailPassword } from '../hooks/useCreateLoginScreenEmailPassword';\n- `5` export function CreateLoginScreenEmailPasswordScreen(): React.JSX.Element {\n- `6` const { run, loading, error, data } = useCreateLoginScreenEmailPassword();\n## src/__tests__/CreateLoginScreenEmailPasswordApi.ts\n\n- `1` // TDD test suite for CreateLoginScreenEmailPasswordApi — written before implementation.\n- `3` import { createLoginScreenEmailPasswordApi } from '../services/CreateLoginScreenEmailPasswordApi';\n- `5` describe('CreateLoginScreenEmailPasswordApi', () => {\n## src/services/CreateLoginScreenEmailPasswordApi.ts\n\n- `1` export class CreateLoginScreenEmailPasswordApi {\n- `7` export const createLoginScreenEmailPasswordApi = new CreateLoginScreenEmailPasswordApi();\n## App.tsx\n\n- `9` <Text style={styles.title}>login-app</Text>\n\n## Findings\n",
  },
  {
    cmd: "incident",
    name: "Incident Commander Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/incident/report.md",
    regenerate: "vectalon incident",
    doc: "# vectalon incident — Incident Brief\n\nPlatform: **unknown**  ·  Root cause: **no-data**  ·  Verdict: **changes-requested**\n\n## Root cause\n\nNo crash log or prior crash report available.\n\n\n## Next steps\n\n- Run vectalon crash --log <path> with the crash log, or run vectalon crash first so an incident can reuse its report.",
  },
  {
    cmd: "train",
    name: "Release Train Automation",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/train/report.md",
    regenerate: "vectalon train",
    doc: "# vectalon train — Release Train (dry-run)\n\nRepos: 1  ·  Verdict: **changes-requested**  ·  Read-only: nothing was modified\n\n## login-app\n\nVersion: 1.0.0  ·  Last tag: rn-v0.7.0-core-v0.1.0  ·  Suggested bump: **minor**  ·  Changelog: ✗  ·  Clean tree: ✗\n\n- [WARNING] No CHANGELOG section for the current version. — Add release notes under the version heading.\n- [WARNING] Working tree is not clean. — Commit or stash changes before cutting the release.\n\n## Findings\n\n### [WARNING] changelog (login-app)\n\nNo CHANGELOG section for the current version.\n\n**Suggestion**: Add release notes under the version heading.\n\n### [WARNING] dirty (login-app)\n\nWorking tree is not clean.\n\n**Suggestion**: Commit or stash changes before cutting the release.\n",
  },
  {
    cmd: "cost",
    name: "Cost Governance Agent",
    verdict: "approved",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/cost/report.md",
    regenerate: "vectalon cost",
    doc: "# vectalon cost — Spend Estimate\n\n> Estimates, not invoices — rates below are explicit assumptions.\n\nTotal: **$0/mo**  ·  Verdict: **approved**\n\n| Item | Amount | Basis |\n|---|---|---|\n\n## Assumptions\n\n- GPU hour: $1.2 (spot-class instance)\n- Tokens: $1/1M input tokens (mid-range hosted model)\n- Data processing: $0.2/GB\n\n## Findings\n\n### [INFO] no-cost-surfaces\n\nNo cost surfaces found — no LoRA config, dataset, or eval cases.\n\n**Suggestion**: Add .vectalon/lora/config.json, datasets, or eval cases to get a spend estimate.\n",
  },
  {
    cmd: "dx",
    name: "DX Scoring Agent",
    verdict: "changes-requested",
    project: "apps/website/demo/login-app",
    reportPath: "docs/vectalon/dx/report.md",
    regenerate: "vectalon dx",
    doc: "# vectalon dx — Developer Experience Score\n\nScore: **34/100 (D)**  ·  Verdict: **changes-requested**\n\n| Axis | Score | Weight | Note |\n|---|---|---|---|\n| README | 0/100 | 10% | No README — new devs start blind |\n| Contributing guide | 0/100 | 8% | No contributing guide |\n| Docs directory | 100/100 | 8% | docs/ populated |\n| CI workflows | 0/100 | 12% | No CI workflows |\n| Test setup | 0/100 | 12% | No test setup |\n| Lockfile | 100/100 | 6% | Lockfile committed |\n| Lint config | 0/100 | 6% | No lint config |\n| Format config | 0/100 | 4% | No editor config |\n| TypeScript strict | 100/100 | 8% | strict mode on |\n| Changelog | 0/100 | 8% | No changelog |\n| Onboarding assets | 0/100 | 6% | No onboarding artifacts |\n| Source complexity | 99/100 | 12% | avg 20 lines/file, no giant-file sprawl |\n\n## Top improvements\n\n- **CI workflows** (+12pts): No CI workflows\n- **Test setup** (+12pts): No test setup\n- **README** (+10pts): No README — new devs start blind\n- **Contributing guide** (+8pts): No contributing guide\n- **Changelog** (+8pts): No changelog",
  },
]
