/**
 * vectalon team brain — Onboarding Assistant (Roadmap 049)
 * Business Source License 1.1 (BSL-1.1)
 *
 * Composes the onboarding brief from the other Team Brain parts — stack,
 * glossary, standards, expertise, decisions, and recent PRs — so a new
 * engineer (or agent) on the project starts from one document.
 */

import type {
  CodingStandard,
  DecisionIndexEntry,
  ExpertiseEntry,
  GlossaryTerm,
  PrKnowledgeEntry,
} from './types'

export interface OnboardingInput {
  projectName: string
  glossary: GlossaryTerm[]
  standards: CodingStandard[]
  expertise: ExpertiseEntry[]
  decisions: DecisionIndexEntry[]
  prKnowledge: PrKnowledgeEntry[]
  rnVersion?: string
  tooling?: string
}

const MAX_GLOSSARY_HIGHLIGHTS = 12
const MAX_STANDARD_HIGHLIGHTS = 8
const MAX_DECISION_HIGHLIGHTS = 10
const MAX_PR_HIGHLIGHTS = 10

/** Render the onboarding brief markdown (docs/vectalon/team/onboarding.md). */
export function renderOnboarding(input: OnboardingInput): string {
  const lines: string[] = []
  lines.push(`# Onboarding Brief — ${input.projectName}`)
  lines.push('')
  if (input.rnVersion || input.tooling) {
    lines.push(`**Stack:** ${[input.tooling, input.rnVersion && `React Native ${input.rnVersion}`].filter(Boolean).join(' · ')}`)
    lines.push('')
  }
  lines.push('## Quick start')
  lines.push('')
  lines.push('- `npx vectalon init` — initialize the harness (or re-scan)')
  lines.push('- `npx vectalon status` — daemon, model, refresh, license at a glance')
  lines.push('- `npx vectalon doctor` — verify toolchain + ecosystem items')
  lines.push('- `npx vectalon serve` — expose project-aware MCP tools to agents')
  lines.push('- `npx vectalon team` — regenerate this Team Brain')
  lines.push('')

  lines.push('## Vocabulary (glossary)')
  lines.push('')
  if (input.glossary.length === 0) {
    lines.push('No domain terms extracted yet — they accumulate as the codebase grows.')
  } else {
    for (const term of input.glossary.slice(0, MAX_GLOSSARY_HIGHLIGHTS)) {
      lines.push(`- \`${term.term}\` — ${term.kind} (${term.count}×)`)
    }
    if (input.glossary.length > MAX_GLOSSARY_HIGHLIGHTS) {
      lines.push(`- …and ${input.glossary.length - MAX_GLOSSARY_HIGHLIGHTS} more — see glossary.md`)
    }
  }
  lines.push('')

  lines.push('## Coding standards')
  lines.push('')
  if (input.standards.length === 0) {
    lines.push('No standards derivable yet.')
  } else {
    for (const standard of input.standards.slice(0, MAX_STANDARD_HIGHLIGHTS)) {
      lines.push(`- **${standard.rule}** — ${standard.detail}`)
    }
    if (input.standards.length > MAX_STANDARD_HIGHLIGHTS) {
      lines.push(`- …and ${input.standards.length - MAX_STANDARD_HIGHLIGHTS} more — see coding-standards.md`)
    }
  }
  lines.push('')

  lines.push('## Who knows what')
  lines.push('')
  if (input.expertise.length === 0) {
    lines.push('No git history to map expertise yet.')
  } else {
    for (const entry of input.expertise.slice(0, 5)) {
      const owns = entry.components.length > 0 ? ` — owns ${entry.components.join(', ')}` : ''
      lines.push(`- **${entry.author}** — ${entry.commits} commit(s) across ${entry.files} file(s)${owns}`)
    }
  }
  lines.push('')

  lines.push('## Active decisions (ADR index)')
  lines.push('')
  if (input.decisions.length === 0) {
    lines.push('No ADRs indexed yet — record decisions in docs/adr/ to grow this.')
  } else {
    for (const decision of input.decisions.slice(0, MAX_DECISION_HIGHLIGHTS)) {
      lines.push(`- **${decision.title}**${decision.status ? ` — ${decision.status}` : ''} (\`${decision.id}\`)`)
    }
  }
  lines.push('')

  lines.push('## Recently shipped (PR knowledge)')
  lines.push('')
  if (input.prKnowledge.length === 0) {
    lines.push('No PR references in recent git history.')
  } else {
    for (const pr of input.prKnowledge.slice(0, MAX_PR_HIGHLIGHTS)) {
      lines.push(`- PR #${pr.pr} — ${pr.title}`)
    }
  }
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('_Generated by `vectalon team` — regenerates deterministically. The glossary, standards, expertise, decisions, and PR docs live next to this file._')

  return lines.join('\n')
}
