/**
 * vc outcomes — engineering outcomes, not feature counts.
 * Business Source License 1.1 (BSL-1.1)
 *
 * Directive #10: stop measuring features; measure outcomes. Every
 * deterministic agent already writes a report.json under docs/vectalon/<agent>/,
 * so the ledger aggregates those committed reports into the counters an
 * engineering manager actually cares about — build failures diagnosed and
 * fixed, PR review issues caught, RN upgrades completed, tests generated,
 * performance regressions detected, issues detected and prevented — and then
 * estimates the developer hours and dollars saved.
 *
 * Sales material is the outcome ledger, not "Vectalon has 47 agents."
 */
import { existsSync, readFileSync, readdirSync, statSync } from 'fs'
import { join } from 'path'

/** The outcome counters — exactly the dimensions the directive lists. */
export interface OutcomeCounts {
  /** Build failures diagnosed from build logs (build-fix reports). */
  buildFailuresDiagnosed: number
  /** Build failures fixed (fix/build-fix reports with an applied verdict). */
  buildFailuresFixed: number
  /** Issues caught in PR review (review reports). */
  prIssuesCaught: number
  /** RN upgrades completed (.vectalon/upgrades/<ts>/ provenance dirs). */
  rnUpgradesCompleted: number
  /** Test files generated by feature runs. */
  testsGenerated: number
  /** Performance regressions detected (score perf findings + profile baselines). */
  perfRegressionsDetected: number
  /** Issues detected across all deterministic scans (sec, arch, a11y, …). */
  issuesDetected: number
  /** Issues prevented — caught by the score/guardrail pass before they land. */
  issuesPrevented: number
}

export const EMPTY_COUNTS: OutcomeCounts = {
  buildFailuresDiagnosed: 0,
  buildFailuresFixed: 0,
  prIssuesCaught: 0,
  rnUpgradesCompleted: 0,
  testsGenerated: 0,
  perfRegressionsDetected: 0,
  issuesDetected: 0,
  issuesPrevented: 0,
}

/**
 * Hours saved per outcome — the honest model behind the savings estimate.
 * These are deliberately conservative per-item estimates of what a human
 * engineer would spend on the equivalent task (diagnosing a build failure,
 * catching an issue in review, upgrading RN, writing a test).
 */
export const OUTCOME_HOURS: Record<keyof OutcomeCounts, number> = {
  buildFailuresDiagnosed: 0.5,
  buildFailuresFixed: 1.0,
  prIssuesCaught: 0.25,
  rnUpgradesCompleted: 8.0,
  testsGenerated: 0.5,
  perfRegressionsDetected: 1.0,
  issuesDetected: 0.25,
  issuesPrevented: 0.5,
}

/** Blended fully-loaded engineering rate (USD/hour) for the savings estimate. */
export const DEFAULT_BLENDED_RATE = 75

export function blendedRate(): number {
  const raw = process.env.VECTALON_BLENDED_RATE
  const n = raw ? Number(raw) : NaN
  return Number.isFinite(n) && n > 0 ? n : DEFAULT_BLENDED_RATE
}

/** Total hours saved from a ledger. */
export function hoursSaved(counts: OutcomeCounts): number {
  return (Object.keys(counts) as (keyof OutcomeCounts)[]).reduce(
    (sum, k) => sum + counts[k] * OUTCOME_HOURS[k],
    0
  )
}

/** Estimated dollars saved = hours × blended rate. */
export function savingsEstimate(counts: OutcomeCounts, rate = blendedRate()): number {
  return Math.round(hoursSaved(counts) * rate)
}

/* ── collectors ─────────────────────────────────────────────────────────── */

interface ParsedReport {
  verdict?: string
  findings?: Array<{ severity?: string; [k: string]: unknown }>
  [k: string]: unknown
}

function readReport(dir: string): ParsedReport | null {
  const p = join(dir, 'report.json')
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as ParsedReport
  } catch {
    return null
  }
}

/** Count findings by severity in a report's findings array. */
function countFindings(report: ParsedReport | null, severities: string[]): number {
  if (!report || !Array.isArray(report.findings)) return 0
  return report.findings.filter(f => severities.includes(String(f.severity ?? 'info'))).length
}

/** List the agent report dirs under docs/vectalon/. */
function agentDirs(root: string): string[] {
  const docs = join(root, 'docs', 'vectalon')
  if (!existsSync(docs)) return []
  return readdirSync(docs)
    .map(name => join(docs, name))
    .filter(dir => existsSync(join(dir, 'report.json')))
}

/**
 * Collect the outcome ledger from committed reports. Every count is derived
 * from real report.json artifacts the deterministic agents already write:
 *
 *   build-fix         → build failures diagnosed (+fixed when the verdict passes)
 *   fix / bug-fix     → build failures fixed
 *   review            → PR issues caught
 *   .vectalon/upgrades→ RN upgrades completed (one provenance dir per run)
 *   feature runs      → tests generated (test files under the run docs)
 *   score             → perf regressions (perf findings) + issues prevented (new problems)
 *   sec/arch/a11y/…   → issues detected (error+warning findings)
 */
export function collectOutcomes(root: string): OutcomeCounts {
  const counts: OutcomeCounts = { ...EMPTY_COUNTS }
  const dirs = agentDirs(root)

  for (const dir of dirs) {
    const agent = dir.split(/[\\/]/).pop() ?? ''
    const report = readReport(dir)
    if (!report) continue

    switch (agent) {
      case 'build-fix':
        counts.buildFailuresDiagnosed += countFindings(report, ['error', 'warning'])
        if (report.verdict === 'approved' || report.verdict === 'passed') {
          counts.buildFailuresFixed += 1
        }
        break
      case 'fix':
      case 'bug-fix': {
        // applied:true means the fix actually touched the tree
        const applied = report.applied
        if (applied === true || (Array.isArray(report.findings) && report.findings.length > 0 && report.verdict === 'approved')) {
          counts.buildFailuresFixed += 1
        }
        break
      }
      case 'review':
        counts.prIssuesCaught += countFindings(report, ['error', 'warning'])
        break
      case 'score': {
        const perf = (report.dimensions as Array<{ id?: string; findings?: Array<{ severity?: string }> }> | undefined)
        const perfFindings = (perf ?? []).find(d => d.id === 'performance')?.findings ?? []
        counts.perfRegressionsDetected += perfFindings.filter(f => f.severity === 'error' || f.severity === 'warning').length
        const newProblems = Array.isArray(report.newProblems) ? report.newProblems.length : 0
        counts.issuesPrevented += newProblems
        break
      }
      case 'sec':
      case 'arch':
      case 'a11y':
      case 'arch-score':
      case 'soc2':
      case 'governance':
      case 'perms':
      case 'tokens':
      case 'deps': {
        const n = countFindings(report, ['error', 'warning'])
        counts.issuesDetected += n
        // approved scans caught nothing new; needs-attention means issues live
        if (report.verdict === 'approved') counts.issuesPrevented += 1
        break
      }
      default:
        break
    }
  }

  // RN upgrades completed — one provenance dir per run under .vectalon/upgrades/
  const upgradesDir = join(root, '.vectalon', 'upgrades')
  if (existsSync(upgradesDir)) {
    counts.rnUpgradesCompleted = readdirSync(upgradesDir).filter(name => {
      const full = join(upgradesDir, name)
      try {
        return existsSync(join(full, 'UPGRADE.md'))
      } catch {
        return false
      }
    }).length
  }

  // Tests generated — test files written by feature-development runs
  const featDir = join(root, 'docs', 'vectalon', 'feature-development')
  if (existsSync(featDir)) {
    const runs = readdirSync(featDir)
    for (const run of runs) {
      const runDir = join(featDir, run)
      counts.testsGenerated += countTestFiles(runDir)
    }
  }

  return counts
}

/** Recursively count test files (.*.test.* / .*.spec.*) under a directory. */
function countTestFiles(dir: string): number {
  let n = 0
  let entries: string[] = []
  try {
    entries = readdirSync(dir)
  } catch {
    return 0
  }
  for (const entry of entries) {
    const full = join(dir, entry)
    try {
      const s = statSync(full)
      if (s.isDirectory()) {
        n += countTestFiles(full)
      } else if (/\.(test|spec)\.(ts|tsx|js|jsx)$/.test(entry)) {
        n += 1
      }
    } catch {
      // broken symlink — skip
    }
  }
  return n
}
