import React from 'react';
import { StyleSheet, Text } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '../components/ui';
import { CreateLoginScreenEmailPasswordScreen } from './CreateLoginScreenEmailPasswordScreen';
import type { RootStackParamList } from '../navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'Debug'>;

/** The golden-replay screen kept reachable — generated by vectalon feature. */
export function DebugScreen(_props: Props) {
  return (
    <Screen>
      <Text style={styles.note}>Generated by vectalon feature — golden replay</Text>
      <CreateLoginScreenEmailPasswordScreen />
    </Screen>
  );
}

const styles = StyleSheet.create({ note: { fontSize: 12, color: '#9ca3af', marginBottom: 16 } });
